### ISSUE TITLE
Jumping on Et Futurum Paths turns them into GT6 Paths (GT6 6.14.23 + Et Futurum 2.4)

### ISSUE THREAD

**Issue by tyrael93** [Roadhog360/Et-Futurum-Requiem#105]
Hello, bit of a minor concern bug, who might actually be a feature.

I've just noticed that if I make an et futurum grass path using a regular vanilla tool and then jump over it, the Et Futurum path turns into a GT6 path. Sort of like jumping over farmland turns it back into dirt. Jumping again over the GT6 path does nothing, as expected.

Is this intended?

Thanks in advance.

**Comment by GregoriusT** [comment]
Lol fully intended, I did that in GT6. XD

It is basically because I have a Walk Speed boost and also some other Path related extra Features like turning into a Slab Form when on "sloped" terrain, so that you dont need to place Wooden Slabs just to make a Path walkable. ;)
