### ISSUE TITLE
Strange ticking chunk error crash

### ISSUE THREAD

**Issue by krallendertoten** [Roadhog360/Et-Futurum-Requiem#112]
**Starting Questions**
- [] This is a mod incompatibility, if I use this in vanilla Forge, with only Et Futurum Requiem installed it works as I'd expect it to.

Not sure, it's not a consistent bug.

_Please specify the actual version... please don't just say "latest", tell me the version number of the mod in-game, or the name the jar had when downloading it._

Version: 2.3.2

If this is a crash, please upload the report:

[crash-2022-02-27_11.17.53-server.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/8149020/crash-2022-02-27_11.17.53-server.txt)

(This doesn't show the whole stack trace)

**Describe the bug**

Generating new chunks, whether with a pregenerator or a player, produces extreme amounts of corrupted/ticking chunks.

**To Reproduce**
1. Go into world
2. Try to go into new chunks
3. Game crashes

**Additional context**

Honestly, I'm not sure what's exactly going on. The reason I suspect this mod in the first place is that its exception handler is constantly in the stack trace from the server, and removing it prevents the crash from happening. I can't reproduce this issue consistently even with identical mods and the same seed in a new world. There isn't even a crash report generated unless I use a pregenerator; without that it just constantly spits out ticking chunk exceptions until I stop the server manually (or kill the instance when testing in singleplayer)
I'll include the entire log from MultiMC, and I can upload a zip with the world and mods if necessary. Apologies for not following the format exactly, it's just kind of hard to isolate the issue since it's so inconsistent.

[stackTrace.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/8149012/stackTrace.txt)

**Comment by Roadhog360** [comment]
https://github.com/Roadhog360/Et-Futurum-Requiem/actions/runs/1870654660

What happens if you use the non-dev jar here under "Package"?

**Comment by krallendertoten** [comment]
That does seem to fix it, thanks. For reference, what was the root cause of the issue?

**Comment by krallendertoten** [comment]
Actually it only fixed it when I use the world in singleplayer. For some reason in my server it still throws a long error about mixins as soon as I try to launch it, resulting in a crash before it even comes up. I took a partial cut of it from the first mention of the mod:

[12:46:03] [main/FATAL] [mixin]: Mixin apply failed mixins.etfuturum.
json:MixinBlockFurnace -> net.minecraft.block.BlockFurnace: org.spong
epowered.asm.mixin.injection.throwables.InvalidInjectionException @In
ject annotation on handler$randomDisplayTickMixin$zza000 could not fi
nd any targets matching 'func_149734_b' in the target class net.minec
raft.block.BlockFurnace. Using refmap mixins.etfuturum.refmap.json
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionExce
ption: @Inject annotation on handler$randomDisplayTickMixin$zza000 co
uld not find any targets matching 'func_149734_b' in the target class
 net.minecraft.block.BlockFurnace. Using refmap mixins.etfuturum.refm
ap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo
.findMethods(InjectionInfo.java:421) ~[Et_Futurum_Requiem-2.4.0-SNAPS
HOT-599839d.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo
.readAnnotation(InjectionInfo.java:172) ~[Et_Futurum_Requiem-2.4.0-SN
APSHOT-599839d.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo
.<init>(InjectionInfo.java:159) ~[Et_Futurum_Requiem-2.4.0-SNAPSHOT-5
99839d.jar:?]

**Comment by Roadhog360** [comment]
I know why, I'll send you another build soon.

**Comment by makamys** [comment]
The first stack trace is the same as the one in https://github.com/Roadhog360/Et-Futurum-Requiem/issues/104, it's a crash in the boat replacer. So disabling `replaceOldBoats` should work as a workaround for that one.
