### ISSUE TITLE
NEI Recipes don't disappear if smoker/blast furnace are disabled. 

### ISSUE THREAD

**Issue by calreveraster** [Roadhog360/Et-Futurum-Requiem#113]
Hello, 

I have the smoker and blast furnace disabled in configs due to already having a pretty heavily-scripted setup for recipes when I implemented the mod. 

However, I've noticed that despite disabling them, the recipes persist in NEI. 

Example: If I select cooked beef in NEI, a smoker recipe option is still visible. 

Would it be possible to have these recipes hidden when the smoker/blast furnace are disabled?

**Comment by tyrael93** [comment]
Currently other mods (Railcraft's machines, for example) have the same issue even if you disable the machine itself, so the way I understand it, the recipes have to be explicitly disabled from being visible with an extra step code-wise, so the mod is working as it usually would, but adding the option to disable them by default would be nice. I do think this might be more on the NEI side of things though.

**Comment by Roadhog360** [comment]
I'm surprised other mods don't do this actually, I'll add it in the next update for you.

**Comment by tyrael93** [comment]
This was marked as resolved, but I can confirm that with both the blast furnace and the smoker disabled

>     #  [default: true]
>     B:enableSmoker=false
>     #  [default: true]
>     B:enableBlastFurnace=false

the recipes are still very much visible when using the latest experimental version
> Et_Futurum_Requiem-2.4.0-SNAPSHOT-8b011b7.jar
![2022-06-01_10 12 30](https://user-images.githubusercontent.com/5557920/171358806-edf9d520-25d2-4cda-bf15-0dc7fdaa813b.png)

**Comment by makamys** [comment]
> 8b011b7

That doesn't look like the latest to me, the last commit is 06bf845.

**Comment by tyrael93** [comment]
aw jeez no nevermind I'm a doofus
I downloaded that version but I was using that to to check stuff in my test instance, while I was using that version for my main one :thinking: 
my bad
unrelated, but I wonder if that's why the amethyst geodes weren't spawning in the skyworld dimension
