### ISSUE TITLE
Placing Multiple Tile Entities Doesn't Swap for Et Futurum Version

### ISSUE THREAD

**Issue by DarianLStephens** [Roadhog360/Et-Futurum-Requiem#114]
**Starting Questions**

Version: Et_Futurum_Requiem-2.3.2

**Describe the bug**
When placing multiple brewing stands in quick succession, some won't change to the Et Futurum version immediately.

**To Reproduce**
1. Get 2 or more brewing stands
2. Place them both within a second or so of eachother
3. At least one is a vanilla brewing stand, usually the second one placed.

**Mod Incompatibilities**
I don't think it's an incompatibility with anything, just events getting lost or something.

**Screenshots**
![2022-03-10_16 03 42](https://user-images.githubusercontent.com/15375876/157593221-5c44a433-fc94-4172-bcfd-40ad29b17080.png)
![2022-03-10_16 03 45](https://user-images.githubusercontent.com/15375876/157593234-313b601a-89ed-48f7-be7b-1df25b752960.png)
![2022-03-10_16 03 43](https://user-images.githubusercontent.com/15375876/157593239-4a7bdfd4-c0f3-425d-a0d1-79657269d2ff.png)
![2022-03-10_16 03 44](https://user-images.githubusercontent.com/15375876/157594923-eb581ebf-2bd8-44d2-8a09-66886603832c.png)

**Additional context**
Nothing I can really think of. Sometimes both seem to change, but not often.
It changes to the proper one eventually, but not until a few seconds have passed at least.

**Comment by Roadhog360** [comment]
I think this should already be fixed in the current in-progress version.

**Comment by Roadhog360** [comment]
https://github.com/Roadhog360/Et-Futurum-Requiem/suites/5375962463/artifacts/168821311
Can you try this build?
Note: This replaces the tile entity when you place it down now, instead of looking through all tile entities. So old tile entities are no longer checked.

**Comment by DarianLStephens** [comment]
Seems to work just fine. Does it mean that old tileentities, like those placed in structures, won't update, though?

**Comment by Roadhog360** [comment]
Yes.
