### ISSUE TITLE
1.7.10 Unable to play unknown soundEvent Et futurum requiem 2.3.2

### ISSUE THREAD

**Issue by quentin452** [Roadhog360/Et-Futurum-Requiem#118]
**Starting Questions**

forge-1.7.10-10.13.4.1614
Et futurum requiem 2.3.2  mod

**Describe the bug**

Spam in the console 
Unable to play unknown soundEvent: etfuturum:entity.boat.paddle_water

**To Reproduce**

1. Choose a boat
2. Move forward with the boat in the water
3. Watch logs

**Screenshot**

https://i.imgur.com/lXtJsoD.png

**Comment by makamys** [comment]
Can you post a full log? There's probably more messages about `entity.boat.paddle_water` in there.

**Comment by quentin452** [comment]
[latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/8585017/latest.log)

**Comment by Roadhog360** [comment]
Are you sure you are really using 2.3.2? Boat wounds worked in 2.3.1. (I quickly skimmed the logs, I am at work.)

**Comment by quentin452** [comment]
ok, yes i am sure

**Comment by quentin452** [comment]
its the 2.3.2 from the github 13 Jan 2022

**Comment by makamys** [comment]
Sorry, I forgot to say I meant `fml-client-latest.log`.

**Comment by quentin452** [comment]
oh ok

**Comment by quentin452** [comment]
[fml-client-latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/8585175/fml-client-latest.log)

**Comment by makamys** [comment]
Oh, actually, I just tested and I can reproduce this. It works fine in the dev build (2.4.0) though, so this will be fixed in the next release.

**Comment by quentin452** [comment]
ok thx
