### ISSUE TITLE
1.7.10 Fetching addPacket for removed entity Et futurum requiem 2.3.2

### ISSUE THREAD

**Issue by quentin452** [Roadhog360/Et-Futurum-Requiem#119]
**Starting Questions**

forge-1.7.10-10.13.4.1614
Et futurum requiem 2.3.2 mod

**Describe the bug**

When I place a boat in the water it writes "Fetching addPacket for removed entity in the console https://i.imgur.com/7zrznOw.png

Sometimes when i spam boat , he can spawn the vanilla boat https://i.imgur.com/iMw0tmo.png

**To Reproduce**
1. Take a boat
2. Put it in the water
3. Watch logs

**Comment by makamys** [comment]
This one also seems to be fixed in 2.4.0's dev build.
![2022-04-28_20 11 49](https://user-images.githubusercontent.com/13667520/165819484-5dd2b71d-ec95-49c8-a098-8a19ed212fe4.png)

**Comment by fnar** [comment]
What was the fix? Was there a commit which addressed this issue?
