### ISSUE TITLE
Does Blocks.lit_redstone_ore even exist? And if it doesn't should all references to it in Code be removed?

### ISSUE THREAD

**Issue by GregoriusT** [Roadhog360/Et-Futurum-Requiem#122]
Does "Blocks.lit_redstone_ore" even exist? I mean inside the Item/Block Registry and the Code Reference. It clearly somehow exists ingame in some weird Schrödinger case.

I just recently noticed that Item/Block ID 74 is unpopulated in Vanilla+Forge without ANY Mods, just an empty Vanilla+Forge Instance and trying to "/give Myself 74", which is Lit Redstone Ore, resulting in the error of that Item not existing. Just to make sure Numerical IDs still work I cheated in ID 73 just fine which was regular Redstone Ore.

I found this Issue due to a GT6 Bug when trying to harvest Lit Redstone Ore, which resulted in a lot of shit not triggering like it was supposed to, thanks to which I found out this Item/Block does not even exist in the Item Registry.

Now I know that at the very least Deepslate Redstone Ore refers to this Block in Code, so I am just going to ask the question if this finding of mine causes any potential Issues? Everything SEEMS to work fine, but it might be worth looking into.

Another thing to do might be just fixing the lack of registration for the Lit Redstone Ore Block, though not sure if that's Et Futurum Requiems Job.

**Comment by Roadhog360** [comment]
Yes it does exist. Its ItemBlock was removed in future versions though.

Not a bug

**Comment by GregoriusT** [comment]
Good to know what became of it, I thought they might have added an ItemBlock to it later on, that's why I posted this here. ^^
