### ISSUE TITLE
Boat velocity is glitchy

### ISSUE THREAD

**Issue by embeddedt** [Roadhog360/Et-Futurum-Requiem#129]
**Starting Questions**

Version: 2.3.1 (also reproduceable with a recent `master` version)

**Describe the bug**

While boat behavior is substantially closer to how 1.9+ function, there is still some sort of desynchronization between the server and client. The boat is frequently teleported several blocks forward/backward and its direction also changes sometimes as well. This issue gets worse the laggier the integrated server becomes. In a modpack, I have had the boat teleport up to 20-30 blocks away from where it was on the client. In these scenarios it is also very difficult to steer accurately towards your destination.

These issues make the boat unsuitable for any sort of long-distance travel.

**To Reproduce**
1. Create a fresh world.
2. Place a boat in an area with open water.
3. Drive the boat around and turn left and right.
4. Try to drive straight.

**Mod Incompatibilities**

No other mods installed.

**Additional context**

Here is a video demonstrating the issue.

https://user-images.githubusercontent.com/42941056/172027977-cf95d3c0-5762-4cf0-ba25-d4587b1a36e5.mp4

Thanks for your hard work on this mod!

**Comment by Roadhog360** [comment]
Known issue, 1.7.10 limitation

**Comment by Roadhog360** [comment]
I should also clarify that while this cannot be fully fixed, I will attempt to mitigate its effects in a future version, I'll admit it is entirely possible to reduce the jitter still.

**Comment by DarianLStephens** [comment]
From my outside perspective of what I've seen when interacting with the boats, it feels like the direction gets desynced more than anything.
So, if you turn, the server and client think the boat's facing different directions, and so the weird movement.
I wonder what would happen if you reworked how the client turning (Or synchronization) worked, or even disabled it entirely and allowed the server to do it?

**Comment by Roadhog360** [comment]
There is a function for getting the server position or something for entities but for some reason rotation doesn't work.
