### ISSUE TITLE
[Feature Request] Post on modrinth

### ISSUE THREAD

**Issue by Jerome226** [Roadhog360/Et-Futurum-Requiem#133]
Would be cool if the mod could be uploaded to [modrinth.com](https://modrinth.com)

**Comment by Roadhog360** [comment]
Feature requests belong in the [discussions](https://github.com/Roadhog360/Et-Futurum-Requiem/discussions) tab. Although I've actually quietly confirmed on a few servers I am in, including my official one, that Modrinth will be replacing CurseForge as a download platform following 2.4.0's release.

**Comment by Jerome226** [comment]
Sorry for posting the request here, i'm happy you are moving to modrinth.
