### ISSUE TITLE
Crash with JET Modpack (most likely mod conficts)

### ISSUE THREAD

**Issue by UeberallGebannt** [Roadhog360/Et-Futurum-Requiem#136]
**Starting Questions**
- [X] This is a mod incompatibility, if I use this in vanilla Forge, with only Et Futurum Requiem installed it works as I'd expect it to.

Version: `Et_Futurum_Requiem-2.4.0-beta-1`
If this is a crash, please upload the report:
latest.log: https://mclo.gs/HSmG3k4
crash-report: https://mclo.gs/lsaqD3g
crash-report (Entities): https://mclo.gs/5TSIwy0

**Describe the bug**
The game starts fine but upon world loading, the game crashes. I had another issue before, related to entities, so I disabled all of them and had the second crash.

**To Reproduce**
1. Start the game using the [JET Modpack](https://www.curseforge.com/minecraft/modpacks/jet)
2. Try to open/create world
3. The game crashes

**Mod Incompatibilities**
Maybe Biomes O' Plenty or Minefactory Reloaded as those appear in the logs.

**Mod List**
Modpack page: https://www.curseforge.com/minecraft/modpacks/jet/files/3846210 
Or see crash-reports/latest.log

**Screenshots**
/

**Additional context**
/

**Comment by Roadhog360** [comment]
Et Futurum does not appear anywhere in the crash log. I see CoFH and there was an incompatibility on that front which will be fixed in beta 2.

**Comment by UeberallGebannt** [comment]
So if I understand this correctly, it is caused by Et Futurum + COFH?
And it will be fixed in the next beta?

**Comment by Roadhog360** [comment]
Likely

**Comment by UeberallGebannt** [comment]
But why did this get closed then? I see that you already have a planned solution, but shouldn't it stay open until it really works?

**Comment by Roadhog360** [comment]
Because if it isn't that, no code from Et Futurum appears in the crash log so it is impossible to actually debug the issue to tell if this mod really causes it.

You can try the fix yourself here: https://github.com/Roadhog360/Et-Futurum-Requiem/suites/7099483002/artifacts/281032944

**Comment by UeberallGebannt** [comment]
As this version allows for me to open a world, it seems to be caused by this issue

**Comment by Roadhog360** [comment]
https://github.com/Roadhog360/Et-Futurum-Requiem/releases/tag/2.4.0-beta-2
