### ISSUE TITLE
Spectator mode is mostly broken when Fisk's Superheroes is installed

### ISSUE THREAD

**Issue by KingOfTheGamesYT** [Roadhog360/Et-Futurum-Requiem#137]
-My mod list is: codechickencore, nei, fastcraft, animation api, adventurekraft, durability show, enchanting plus, this mod, fisk superheroes, mlp mythical creatures, ichunutil, iron chests, iron furnaces, journey map, kingdoms of the overworld, lucky block, mouse tweaks, mutant creatures, neat, notenoughids, orespawn, orespawn dangerzone, pandoras box, rainbow world, kingmod, shinyfood, steves universe, tabula, tales of kingdoms, vein miner, waila, wawla, waila harvestability  and baubles

_in version 2.4.0

**Describe the bug**
With these bugs installed Spectator works only by making you invisible

**To Reproduce**
1. use these mods
2. do /gamemode 3

**Screenshots**
![image](https://user-images.githubusercontent.com/53309562/177020512-2b6a6a0f-a1ba-48df-a13d-0dfc605fd71d.png)

**Comment by Roadhog360** [comment]
I've contacted the author. Unfortunately there's not much else I can do to investigate right now, as the mod appears to be closed-source. I've pointed them to this page, hopefully we can get a response and a fix.

**Comment by Roadhog360** [comment]
Closing this as the fault is Fisk's Heroes, the author has confirmed a fix and told me it will be released next update.
