### ISSUE TITLE
bug about industrialcraft2

### ISSUE THREAD

**Issue by kchzh1234** [Roadhog360/Et-Futurum-Requiem#141]
_in version 2.4.0

Describe the bug
With these bugs installed generators don't create EU
the bug has been confirmed in org/ejml
![%R41NYWMJYA I(0UEK6I~Y6](https://user-images.githubusercontent.com/108740939/177474609-b7593f95-8a04-4189-b794-6c9244f96564.png)

**Comment by Roadhog360** [comment]
Is this mod open source? I cannot seem to find the source code.

**Comment by kchzh1234** [comment]
It is close source

**Comment by Roadhog360** [comment]
Can you provide a mod list and logs when trying to generate EU?

Are you sure it is an Et Futurum issue?

**Comment by kchzh1234** [comment]
I ruled out one by one to find out the issue
![1657085965088](https://user-images.githubusercontent.com/108740939/177477129-a1aabf6f-03e2-4f77-bda2-7be3ffa58074.jpg)
![1657085986557](https://user-images.githubusercontent.com/108740939/177477136-631280af-208b-4863-9329-4211b97e82a2.jpg)
![1657086006109](https://user-images.githubusercontent.com/108740939/177477138-2d20236f-8d22-4559-8c3f-3b5803d84de6.jpg)
![1657086019434](https://user-images.githubusercontent.com/108740939/177477140-192e8b37-49de-4f40-949d-a2fb63f39645.jpg)
![1657086029351](https://user-images.githubusercontent.com/108740939/177477143-79ac961a-bf14-43df-92cd-f432352422c2.jpg)
![1657086037815](https://user-images.githubusercontent.com/108740939/177477147-19b22b5c-9d6e-421c-95ae-3998f762871e.jpg)
![1657086050322](https://user-images.githubusercontent.com/108740939/177477151-9c02c990-fdd6-478e-8dde-0ae904176c38.jpg)
[logs.zip](https://github.com/Roadhog360/Et-Futurum-Requiem/files/9051932/logs.zip)

**Comment by GregoriusT** [comment]
ejml is a requirement for the old IC2, unsure where Player uses that junk, but it MIGHT be for the Energy Net.

On that Screenshot what is the Machine on the Left? Is that a Charging Table? Did that come with the Advanced Solar Panel Mod?

It could always be the Issue of the Energy Net randomly ceasing to work regardless which Mods are installed, which might be problematic when trying to find the Issue.

I know @Speiger technically has access to the IC2 Source, but I am not sure if he is gonna help with this.

**Comment by kchzh1234** [comment]
the Machine on the Left is Order Infused Triple Compressed Solar Panel in Electro-Magic Tools mod

**Comment by Roadhog360** [comment]
Is this Et Futurum's fault? Have we caused this bug?

> @GregoriusT Player was basically obsessed with matrix calculations back then. He uses that to calculate out how much energy goes where and how much loss is applied. Also this library is used for the windcalculation.
> 
> But yeah... Eh lets say you either have a corrupt ic2 release (download corruption) or player uploaded a bad build and nobody noticed or 5k other things.
> 
> Basically yeah the library isn't fully loaded for whatever reason...

**Comment by Speiger** [comment]
@Roadhog360 i doubt it.
But I can be wrong. The game spams crashlogs that says "Libraries are missing" so if he/she takes out your mod and the spam still happens then its not your fault, otherwise it is.

**Comment by kchzh1234** [comment]
it's back to normal

**Comment by kchzh1234** [comment]
the issue is in this file in your mod
![C%UB`FO~GY ZGJXMCAE}ERS](https://user-images.githubusercontent.com/108740939/177579144-1fcce71a-81fe-4cf3-989d-c08303da4862.png)

**Comment by kchzh1234** [comment]
![C%UB`FO~GY ZGJXMCAE}ERS](https://user-images.githubusercontent.com/108740939/177579220-03628148-f654-4280-8d5d-50d6aa95d518.png)

**Comment by Roadhog360** [comment]
It is a conflict with Mixins or the other file in org. As these are required libraries for my mixins to work, there is nothind I can do about this.

Other mods like BugTorch or Flying Cullers probably also trigger this issue as they use Mixins.

**Comment by Speiger** [comment]
@Roadhog360 just downloaded the jar, you also include the same library that player loads externally.

**Comment by Speiger** [comment]
Suggestion, from what I remember player loads the jar into a folder (i think 1.7.10) and loads it externally.
How about you try to use the same method and if ic2exp provides a version you use that instead?

This is just a idea though @OvermindDL1 would be here the better person since I doubt @GregoriusT has the experience required to do such a thing.
And I am basically so far out of 1.7.10 that I am basically useless with this xD

**Comment by Roadhog360** [comment]
Huh, I was wrong, it's not used anywhere. Et Futurum includes a few embedded libraries but at some point ejml made its way on there despite not being used by anything. I'm going to see if a build works.

**Comment by Roadhog360** [comment]
Main jars compile but for some reason dev jars now fail to compile without it.

**Comment by Roadhog360** [comment]
https://github.com/Roadhog360/Et-Futurum-Requiem/suites/7242557968/artifacts/290743486
Try this @kchzh1234, this should work. Use the jar that isn't labeled "dev"

**Comment by GregoriusT** [comment]
I just realized, it could ALSO be a case of "some other Mod includes the IC2 API in their Jar File", in case that hint helps at all whatsoever.

**Comment by Roadhog360** [comment]
The user said it works without Et Futurum, so it was ejml in Et Futurum.

**Comment by kchzh1234** [comment]
it works

**Comment by OvermindDL1** [comment]
Since I was summoned anyway via:

> This is just a idea though @OvermindDL1 would be here the better person since I doubt @GregoriusT has the experience required to do such a thing.

Just as a note, don't include other libraries classes inside your own jar, include them adjacent to your jar, or if you do not need to re-export them then shade them in (forgegradle has built in functionality to do this for you) so that they get remapped into your local namespace so there will be no conflicts.

**Comment by Roadhog360** [comment]
ejml wasn't even supposed to be there. A few commits ago it randomly popped back in the build.gradle somehow even though I didn't add it.

**Comment by OvermindDL1** [comment]
So I noticed, but still figured its useful to pop in this information in case it comes up in someones google search.  ^.^
