### ISSUE TITLE
Geodes can generate submerged

### ISSUE THREAD

**Issue by KibaTheBarbarian** [Roadhog360/Et-Futurum-Requiem#149]
ver of mod Et Futurum Requiem 2.4.0
ver of Forge 10.13.4.1614
java 1.8.0 321 64bit
For some reason to geo spawn in the water still and they are not touching anything maybe it's a gravel idk

![2022-07-14_22 32 00](https://user-images.githubusercontent.com/20373705/179135351-6ea01252-db48-4ae1-b304-94315adb3029.png)

**Comment by OMGICE** [comment]
I also encountered this problem. 😂

**Comment by makamys** [comment]
This should be fixed as of cdedec5.
