### ISSUE TITLE
Shift-clicking items from the hotbar into a brewing stand with an empty fuel meter and empty fuel slot deletes them

### ISSUE THREAD

**Issue by Lariari** [Roadhog360/Et-Futurum-Requiem#160]
Version: 2.4.0

**Describe the bug**
Items shift-clicked into the new Brewing Stand are deleted.

**To Reproduce**
1. Open a 'new' Brewing Stand with no fuel (Blaze Powder)
2. Shift-click any item that ISN'T Blaze Powder
3. The item will be deleted, this does not happen when shift-clicking Blaze Powder

**Comment by Lariari** [comment]
The version this bug is happening in is 2.4.0

**Comment by Roadhog360** [comment]
[simplescreenrecorder-2022-08-14_11.05.51.webm](https://user-images.githubusercontent.com/11903511/184545383-d6e82fca-0d2e-4fcb-9318-24a9ac088662.webm)

**Comment by Roadhog360** [comment]
Please post a video of you reproducing the bug, and mods list.
Ensure you are actually on 2.4.0.

**Comment by Lariari** [comment]
The brewing stand must have no fuel in it, I mentioned this initially. Here is a recording with nothing but Forge installed

https://user-images.githubusercontent.com/43853367/184948590-f5a3421f-70e7-423f-9562-fdf435bcffb2.mp4

**Comment by Roadhog360** [comment]
Hello, in my video you can see I try with and without fuel and I still cannot reproduce this.

**Comment by GregoriusT** [comment]
Can I see the FML log? Forge has a setting that deletes erroring TileEntities, and it MIGHT cause the brewing Stand TileEntity to be deleted without the Brewing Stand itself vanishing.

**Comment by Lariari** [comment]
> 

When I say fuel I mean this bar being full
![fuel](https://user-images.githubusercontent.com/43853367/184974075-9615dcd5-bb2b-4ad5-894d-5dd64ae0a921.png)
.

**Comment by Lariari** [comment]
> Can I see the fml-client-latest.log? Forge has a setting that deletes erroring TileEntities, and it MIGHT cause the brewing Stand TileEntity to be deleted without the Brewing Stand itself vanishing.
[latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/9354245/latest.log)

**Comment by GregoriusT** [comment]
Why do people always give the latest.log when i specifically ask for fml-client-latest.log ?

**Comment by Lariari** [comment]
> Why do people always give the latest.log when i specifically ask for fml-client-latest.log ?

Because that's all there is in the logs directory, where most people look for logs.
![logs](https://user-images.githubusercontent.com/43853367/185010558-685f0127-0b73-4986-b2b5-911dd924bf91.png)

**Comment by Roadhog360** [comment]
> > Hello, in my video you can see I try with and without fuel and I still cannot reproduce this.
> 
> When I say fuel I mean this bar being full ![fuel](https://user-images.githubusercontent.com/43853367/184974075-9615dcd5-bb2b-4ad5-894d-5dd64ae0a921.png)

Confirmed

**Comment by Roadhog360** [comment]
Weird, I am looking at the code for the new brewing stand's transferStackInSlot and nothing refers to the fuel level for shift clicking. I'm hoping this doesn't turn into another SoS issue...

**Comment by GregoriusT** [comment]
The Issue likely is not the shiftclicking itself, but might actually be the Recipe Logic instantly reacting to the Item you insert? Or did you already find the actual Issue? It was hard to see in that commit because it rewrote the entire shiftclick logic.

-----

> Because that's all there is in the logs directory, where most people look for logs.

Wait WHAT?! This is what is SUPPOSED to be in the logs Folder along with the .log.gz things:

> fml-client-1.log
> fml-client-2.log
> fml-client-3.log
> fml-client-latest.log
> fml-junk-earlystartup.log
> latest.log

And you are telling me you have Forge installed, which to my knowledge is definitely a prerequisite for installing Et Futurum Requiem, and these Forge Logs do not exist in the logs Folder?

Did Windows somehow end up hiding the Files? Can you look at the content of this Folder with viewing hidden Files enabled? I just have to know what exactly went wrong there...

**Comment by makamys** [comment]
My guess is that some launchers (Technic in this case) use a custom log4j config that cause the `fml-client-latest.log` file to not get created.

**Comment by GregoriusT** [comment]
Gotta love just blindly killing all the logging instead of doing the sensible thing and replacing it with a basic System.out.println to a basic text File...
