### ISSUE TITLE
InvocationTargetException on net.minecraft.world.World / WorldServer (Mixin-related?)

### ISSUE THREAD

**Issue by lordmuff** [Roadhog360/Et-Futurum-Requiem#161]
**Starting Questions**
- [X] This is a mod incompatibility, if I use this in vanilla Forge, with only Et Futurum Requiem installed it works as I'd expect it to.

_Please specify the actual version... please don't just say "latest", tell me the version number of the mod in-game, or the name the jar had when downloading it._
Version: 2.4.0
If this is a crash, please upload the report:
Does not produce a crash log, crashes before the server initializes, when mixins are happening.

**Describe the bug**
_A clear and concise description of what the bug is._
Server crashes with an InvocationTargetException on net.minecraft.world.WorldServer or net.minecraft,world.World

**To Reproduce**
Boot a Forge 10.13.4.1614 server with the mod list provided below.

**Mod Incompatibilities**
_If this was a mod incompatibility, what are the possible suspects? If you're not 100% sure, you can still list your suspected mods here, just tell me if you're not certain they actually cause it._
Friend says that removing ReAuth fixed it for his server setup, but I had removed it in my server side testing because IIRC it was a client side mod that doesn't belong on a server.
Also, the error itself seems to be from some mixin / ASM conflict with something modifying net.minecraft.world.WorldServer or net.minecraft,world.World, i looked in the access transformer and the only world related stuff i found was what i assume to be the Amethyst geode generation code; Lines 65 to 70. Probably from something world / world-gen related?

**Mod List**
_If you have posted a crash report above or this is not a mod incompatibility, you can skip this. If you're filling this out because of a mod incompatibility that isn't a crash, crash reports generate a mods list you can copy. Please use Pastebin if it is large. If you don't have an up-to-date crash report, you can hold F3 + C for 10 seconds while in a world to crash the game, which will give you a crash report._
My server modlist can be found uploaded to my Google Drive here: https://drive.google.com/file/d/1Iey-WGRpKXJwkmoeZHkqW1nPd1E1xf3M/view?usp=sharing

**Screenshots**

**Additional context**
Any other info I may have missed. If you know the code which causes the error please post a link to it.
Like previously mentioned, it seems to be something mixin or ASM related, as it crashes when they are initializing before the server initializes. Affects net.minecraft.world.WorldServer or net.minecraft,world.World, my best bet is that it could be from your Amethyst geode generation code, as mentioned above. May also want to involve Greg, Reika, or HBM as their mods are currently being used and they'd know their mods best.

**Comment by makamys** [comment]
Since there's no crash log, can you post your `fml-server-latest.log`?

**Comment by lordmuff** [comment]
Here you go!
[fml-server-latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/9261826/fml-server-latest.log)

**Comment by embeddedt** [comment]
I think installing Mixingasm might fix this.

**Comment by lordmuff** [comment]
> I think installing [Mixingasm](https://github.com/makamys/Mixingasm/releases/tag/v0.2.1) might fix this.

Will try this and report back! Thank you!

**Comment by Roadhog360** [comment]
@lordmuff Sorry to ping, I wanted to ask if this worked for you.

**Comment by lordmuff** [comment]
> @lordmuff Sorry to ping, I wanted to ask if this worked for you.

I can confirm this works, the server boots up. Thank you!
