### ISSUE TITLE
Spectator mode crashes on inventories

### ISSUE THREAD

**Issue by DrParadox7** [Roadhog360/Et-Futurum-Requiem#162]
**Starting Questions**
- [ ] This is a mod incompatibility, if I use this in vanilla Forge, with only Et Futurum Requiem installed it works as I'd expect it to.

_Please specify the actual version... please don't just say "latest", tell me the version number of the mod in-game, or the name the jar had when downloading it._
Version: Et_Futurum_Requiem-2.4.0.jar
If this is a crash, please upload the report:

[crash-2022-08-04_18.35.13-server (1).txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/9263800/crash-2022-08-04_18.35.13-server.1.txt)

**Describe the bug**
Crash opening chests in spectator on a server 

**To Reproduce**
1. Go on Spectator mode on a server
2. Open a chest
3. Profit

**Comment by Roadhog360** [comment]
Your instructions are innacurate, step 3 should be "trolled"

**Comment by GregoriusT** [comment]
Actually the Instructions are:

1. Open Chests in Spectator Mode
2. ???
3. Profit!
