### ISSUE TITLE
Added drops don't respect doMobLoot gamerule

### ISSUE THREAD

**Issue by connor135246** [Roadhog360/Et-Futurum-Requiem#168]
Version: 2.4.0

**Describe the bug**
The following changes to drops still happen even if  the "doMobLoot" gamerule is false:
- Sheep dropping mutton
- Charged creeper explosions dropping mob heads
- Mobs killed by the wither dropping wither roses, if the wither rose can't be placed as a block (this is actually a vanilla bug as well: https://bugs.mojang.com/browse/MC-154922)

**To Reproduce**
1. Set the "doMobLoot" gamerule to false
2. Kill a sheep
3. The sheep drops Et Futurum Requiem mutton anyway

**Additional context**
https://github.com/Roadhog360/Et-Futurum-Requiem/blob/3dfefd648b077915a0c5f82bde625d6d1dd7947d/src/main/java/ganymedes01/etfuturum/core/handlers/ServerEventHandler.java#L773

**Comment by Roadhog360** [comment]
Wither roses still dropping is intentional, it is supposed to place a block, but if the block can't be placed it is dropped as an item instead. Placed blocks do not count as mob loot.
It is hard to tell if that is intentional. So for now I won't fix that. I will look at the other two though.

**Comment by Roadhog360** [comment]
1 and 2 fix. 3 remains as won't fix for now.
