### ISSUE TITLE
Entity Render Distance mod don't work

### ISSUE THREAD

**Issue by Sanbursess** [Roadhog360/Et-Futurum-Requiem#169]
version-2.4.0
https://www.curseforge.com/minecraft/mc-mods/entity-render-distance-extender
Entity Render Distance mod don't work.
I can't find config to change that. When I remove your mod, Entity Render Distance mod will work.

**Comment by Roadhog360** [comment]
Hoping I'll be able to look into this, but as their mod is closed source it isn't easy to see what they are doing.

The second report should be a separate issue.

**Comment by Sanbursess** [comment]
I'm sorry I didn't go into detail, My English is very poor. 
Mod loading does not crash, but when I use your mod in my modpack, Entity Render Distance mod is not work.
Whatever I change the config(EntityRenderDistanceExtender.cfg), Entity render distance can not change.

**Comment by Roadhog360** [comment]
I already figured what you meant and I'm telling you I'm not sure if I will be able to fix it.

Please open the second issue as a separate ticket.

**Comment by makamys** [comment]
Try adding [Mixingasm](https://github.com/makamys/Mixingasm/releases) to your pack. I reproduced your issue, and this fixed it for me.

In general, mods using mysteriumlib (e.g. Entity Render Distance Extender) need Mixingasm to work properly with mods that use Mixin (e.g. Et Futurum Requiem).

**Comment by Sanbursess** [comment]
@makamys 
Thanks makamys. Mixingasm mod fix that.

**Comment by Roadhog360** [comment]
Will keep this open for now unless we can't fix it from our end.

**Comment by Roadhog360** [comment]
Ok
