### ISSUE TITLE
End Stone Bricks Recipe Wrong

### ISSUE THREAD

**Issue by Sanbursess** [Roadhog360/Et-Futurum-Requiem#170]
version-2.4.0
![1](https://user-images.githubusercontent.com/104017558/185907922-d2f077ae-a077-45ee-b41f-b4426bbb3a36.png)
The recipe output one End Stone Bricks, it should output four.

**Comment by Roadhog360** [comment]
🤔
Is that end city from ManaMetal?

**Comment by Sanbursess** [comment]
No, I built it. I use Ruins mod to save and spawn this end city.
https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system
