### ISSUE TITLE
Spectator checks on fake players

### ISSUE THREAD

**Issue by DrParadox7** [Roadhog360/Et-Futurum-Requiem#172]
**Version**
Et_Futurum_Requiem-2.4.0.jar

**Crash Report:**
[crash-2022-08-27_18.04.52-server.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/9438483/crash-2022-08-27_18.04.52-server.txt)

**Describe the bug**
Et Futurum gets ignored by some fake players when asked if they are a spectator.
Tantrum ensues.

**To Reproduce**
Can't be reliably and intentionally reproduced so far.

**Mod List**
https://modrinth.com/modpack/the-lost-era/version/1.5.2a

**Comment by makamys** [comment]
From the crash log, it looks like this happens when a zombie attacks an AM2 dummy.

**Comment by embeddedt** [comment]
I fixed this already but the fix came after 2.4.0.

https://github.com/Roadhog360/Et-Futurum-Requiem/commit/03a24cfbb15028ee9d793ed0a818235e62bf2b71
