### ISSUE TITLE
Quartz Bricks Recipe Wrong

### ISSUE THREAD

**Issue by OMGICE** [Roadhog360/Et-Futurum-Requiem#181]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [x] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
> _Specify the actual version, please don't just say "latest", tell us the version number of the mod in-game, or the name the jar had when downloading it._

Et_Futurum_Requiem-2.4.1-SNAPSHOT-2e3fcd8

### Describe the issue (IMPORTANT)
> _A list of steps to reproduce the issue may be helpful too. Screenshots could also prove beneficial for visual issues._

The recipe output one Quartz Bricks, it should output four.

![2022-09-14_16 56 30](https://user-images.githubusercontent.com/106000018/190109500-8b2f6c42-af29-4901-8530-66044351d049.png)

### Mod list (OPTIONAL)
> _Crash reports contain the mod list to copy. Please use Pastebin or Gist if it is too large. If you don't have a crash report, open any world and hold F3 + C for 10 seconds to crash the game manually._

### Additional Context (OPTIONAL)
> _Any other info that may have been missed? If you suspect other mods to cause this issue, list them here and tell us why you suspect each of them._

**Comment by Roadhog360** [comment]
Bruh how tf do these recipes keep getting changed from 4 to 1
