### ISSUE TITLE
the enchantment table does not work for the activation ritual from the Extra Utilities mod

### ISSUE THREAD

**Issue by Gisellle** [Roadhog360/Et-Futurum-Requiem#183]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [ ] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

 Version number of Et-Futurum-Requiem (IMPORTANT)
> _Specify the actual version, please don't just say "latest", tell us the version number of the mod in-game, or the name the jar had when downloading it._
 its 1.7.10

### Describe the issue (IMPORTANT)
> _A list of steps to reproduce the issue may be helpful too. Screenshots could also prove beneficial for visual issues._
the mod Extra Utilities dose not recognize the Et-Futurum enchantment table as an enchantment table for the activation ritual.
If I shift right click on the table using the division sigil it dose not provide the requirements for the ritual or activate the ritual if the requirements are met

### Mod list (OPTIONAL)
> _Crash reports contain the mod list to copy. Please use Pastebin or Gist if it is too large. If you don't have a crash report, open any world and hold F3 + C for 10 seconds to crash the game manually._

### Additional Context (OPTIONAL)
> _Any other info that may have been missed? If you suspect other mods to cause this issue, list them here and tell us why you suspect each of them._

**Comment by tyrael93** [comment]
Interesting, I was wondering if that was the case. Hopefully it's an easy fix.

**Comment by Roadhog360** [comment]
I cannot fix this from my end, which is why there are config options provided for the replacement of tile entities.

**Comment by GregoriusT** [comment]
Why exactly do you override the Table itself? Cant you just override the rightclick Event to spawn your own GUI of the Table?

**Comment by Roadhog360** [comment]
Probably not due to tile entity stuff, not sure.

Won't try though because it's from OG Et Futurum, I didn't do it so now I can't remove old blocks.

**Comment by DarianLStephens** [comment]
You have a system to replace blocks in the world. If you made this work using the vanilla block, couldn't you turn that system around to restore the vanilla version in peoples' worlds?

**Comment by Roadhog360** [comment]
There are already config options available that do this.

**Comment by embeddedt** [comment]
FYI, if you install ArchaicFix, it will patch Extra Utilities to recognize more enchantment tables.

**Comment by tyrael93** [comment]
oh neat
