### ISSUE TITLE
creative tab crash

### ISSUE THREAD

**Issue by KibaTheBarbarian** [Roadhog360/Et-Futurum-Requiem#188]
A crash happen with both ver of the mod.Turning off TippedArrows fixed it happens when I go into the creative tab with the Tipped arrows the mod by itself and Non mixins version with gas station

Et_Futurum_Requiem-2.4.1.jar both ver download from discord from Roadhog360

When I go into the creative tab with the Tipped arrows the mod by itself and Non mixins version with gas station

https://pastebin.com/Xy5AGMwB

**Comment by Roadhog360** [comment]
This error is confusing, in the first paragraph you say it is with both versions, but in the last you say it's with the no mixin version. Which is it?

**Comment by GregoriusT** [comment]
Very obvious Nullpointer there, your PotionHelper returns NULL instead of a List of Potions (in certain cases), this is completely unrelated to mixins or anything, just a plain code error, nothing else.

I suggest just always returning an empty List, or adding a null check.

**Comment by Roadhog360** [comment]
It's the same code as vanilla potions so if they don't need it why do I?

**Comment by GregoriusT** [comment]
Maybe you are adding tipped Arrows that DONT have a potion effect to the Creative Tabs? Also a lot of Mojangs later Code is different, so I would not rely on it.

**Comment by Roadhog360** [comment]
I said I copied it from potions, which are in 1.7.10 code. This is the same 1.7.10 code.

**Comment by GregoriusT** [comment]
Well, do you REALLY want to rely on the safety of mojangs code? Because I would not. There has been Item duplication glitches in the Game since ages just because they were too dumb to write a simple swapVariables function correctly...

**Comment by Roadhog360** [comment]
![image](https://user-images.githubusercontent.com/11903511/195963125-e77f8512-db0c-4b8a-b3f6-407a9fd177c5.png)

**Comment by KibaTheBarbarian** [comment]
try it with just mod on it own https://pastebin.com/S0LqbSBa they did say the crash didn't happen if it was in there Modpack but on it own it will crash

**Comment by GregoriusT** [comment]
Yeah no wonder because I'm pretty sure Chickenbones did mess with a bunch of random vanilla things to fix Bugs like this one. I bet it does crash in vanilla too with certain custom potions, and if those would show up in NEI, then NEI would crash, so that is why it probably got fixed.

Also if everything about that function always returns a new ArrayList, why is there even a conditional for creating it in the first place? Wouldn't that be easy to just optimize that conditional part out of the loop?

**Comment by makamys** [comment]
Right. You get a crash if you run Et Futurum without NEI, but with NEI, the error gets caught, but still printed in the log:
```
[12:42:14] [Client thread/ERROR] [NotEnoughItems]: Error loading sub-items for: ganymedes01.etfuturum.items.ItemArrowTipped@2795f288. Tab: etfuturum.items
java.lang.NullPointerException
	at ganymedes01.etfuturum.items.ItemArrowTipped.getPotionEffects(ItemArrowTipped.java:62) ~[ItemArrowTipped.class:?]
```

NEI is added as a dependency by the build script in the dev environment, so if you were testing there, it makes sense you didn't get the crash.

**Comment by makamys** [comment]
Just looked at it, and this is false:

> This is the same 1.7.10 code.

The original `ItemPotion` code calls `PotionHelper.getPotionEffects` directly in `getSubItems`. Your code has an extra step, it transforms the result in `ItemArrowTipped#getPotionEffects` to reduce the potion effect durations. Only, this extra code was missing a null check.

**Comment by Roadhog360** [comment]
How does it have null results when there is a null check in that code?

**Comment by GregoriusT** [comment]
Simple, because that null check is in the wrong location, and it has always been in the wrong location, that is why NEI had to fix the Issue.

**Comment by KibaTheBarbarian** [comment]
I'm happy we got this fixed

**Comment by makamys** [comment]
`PotionHelpers.getPotionEffects` sets a variable to null, then does some stuff that may or may not change the value of the variable, then returns the variable. Therefore, it can return null. That's all there is to it.

You can think of it this way: `ItemPotion#getSubItems` calls `getPotionEffects` with all kinds of parameters, including invalid ones, and just ignores the result if it's invalid. So mods have to do the same. Blame Mojang, not me.
