### ISSUE TITLE
 Something is wrong with the arrows

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#189]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [x] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
> _Specify the actual version, please don't just say "latest", tell us the version number of the mod in-game, or the name the jar had when downloading it._
2.4.1 (discord)

### Describe the issue (IMPORTANT)
> _A list of steps to reproduce the issue may be helpful too. Screenshots could also prove beneficial for visual issues._

Firstly, arrows with effects are NOT ALL displayed in the creative tab, I tried to make an arrow using a cauldron and it worked, but the arrow had an id of "4513:8266".
I wrote a drop script, but it gave an error, then I tried to get it through the 'give' command, but it told me that the item with this id does not exist.

 I have no idea how, but I can play my modpack without #188, BUT if I only play with one et futurum, it crashes with this error.
Also if I write "give 4513" without : then I get "Uncraftable arrow" or something like that

## Here are screenshots where I can't get this arrow via give

![Jre1 8 0_341 Screenshot 2022 10 13 - 14 28 29 53](https://user-images.githubusercontent.com/110309314/195587889-2c03fd7f-4407-43b6-8e5b-50cd99bfc3b4.png)

![Jre1 8 0_341 Screenshot 2022 10 13 - 14 30 22 96](https://user-images.githubusercontent.com/110309314/195587902-b6ea5761-f050-4886-b05e-e1c41be7af2d.png)

![Jre1 8 0_341 Screenshot 2022 10 13 - 14 30 28 02](https://user-images.githubusercontent.com/110309314/195587911-12a37eee-b989-495a-b405-5452d0cdc0ca.png)

**Comment by GregoriusT** [comment]
You cannot use numerical Item IDs in the give command, you have to use the official name of the Item. I do not know exactly which name the Item has but it will look like "etfuturum:arrow", then you need to type a space and enter the Stacksize (1 to 64) and the Metadata (the Metadata is that 8266 thing)

**Comment by kotmatross28729** [comment]
And what should I write in the script then, if it accepts only numeric identifiers?

**Comment by GregoriusT** [comment]
What do you use to write that script? which mod has this scripting ability?

**Comment by kotmatross28729** [comment]
I'm trying to drop a stray mob through mob properties, but I don't understand anything, that is, no, you can not write a numerical identifier there, in short, here's my script

{
  "_name": "etfuturum.stray",
   "drops":
 [
{"function": "add","id": " 4513:8266","damage": "0", "count": "0~1"}
 ],
  
  "pre_stats": [],
  "stats":
  [
{ "function": "modifier", "attribute": "generic.movementSpeed", "value": 0.03},
{ "function": "modifier", "attribute": "generic.attackDamage", "value": 5},
        { "function": "modifier", "attribute": "generic.maxHealth", "value": 20}
  ]
}


I want it to drop an arrow of slowness when it dies.
As I figured out, you can't write id:metadata there

if you know something about mob properties, can you tell me how to do it?

**Comment by kotmatross28729** [comment]
Oh, if I just write 4513 there, then the script will work, but a rather strange arrow will fall out of it

![Jre1 8 0_341 Screenshot 2022 10 13 - 16 07 47 56](https://user-images.githubusercontent.com/110309314/195605243-9cebf8aa-05a7-4451-b64b-e7c2e2d50b74.png)


![Jre1 8 0_341 Screenshot 2022 10 13 - 16 07 56 32](https://user-images.githubusercontent.com/110309314/195605020-e3f844c1-5377-4faf-a3b7-19ae4072915f.png)

**Comment by Roadhog360** [comment]
First of all, that is not how that command works at all. The first input should be the player, the second is the id, which can actually be numerical or namespaced, then after that goes the quantity, and then finally the meta value.

**Comment by Roadhog360** [comment]
This seems to be an issue that's not actually related to my mod, it seems you're having issues with an outside script. You are free to continue the conversation here but the issue will be closed.

**Comment by Roadhog360** [comment]
As a side note, the script should really be using the namespace id, not the numerical one. The numerical ID is changes with every different world, so it is ill-advised to do that.

**Comment by kotmatross28729** [comment]
Wait, what about displaying arrows in the creative tab?

**Comment by Roadhog360** [comment]
I believe that's not quite working right now.

**Comment by kotmatross28729** [comment]
and yes, I can use

{"function": "add","id": "etfuturum:tipped_arrow","damage": "0","count": "0~1"}
 
 Instead of

{"function": "add","id": " 4513","damage": "0", "count": "0~1"}


but I don't know where to write the metadata, because if i write:

{"function": "add","id": "etfuturum:tipped_arrow 8266","damage": "0","count": "0~1"} or something similar

then the script will not work

maybe I'm looking at it badly, but the wiki doesn't say anything about metadata, there are only examples using the name of the item, such as minecraft:gold_ingot, and nothing about minecraft:spawn_egg, for example, that needs metadata

**Comment by Roadhog360** [comment]
Damage and metadata are functionally the same. Both terms are used interchangeably, and they mean the same thing. Set "damage" to the meta value you want.

**Comment by GregoriusT** [comment]
This is probably what you want

{"function": "add","id": "etfuturum:tipped_arrow","damage": "8266", "count": "1"}

**Comment by kotmatross28729** [comment]
Oh wow, thank you so much!!!

**Comment by Roadhog360** [comment]
Changing close type

**Comment by Roadhog360** [comment]
Turns out tipped arrows didn't actually use meta values for their potion effects. This has been fixed for the upcoming release.
