### ISSUE TITLE
我的世界崩潰了

### ISSUE THREAD

**Issue by zxcvbnma54** [Roadhog360/Et-Futurum-Requiem#193]
### Please check any boxes that apply to you and your issue

- [√] I use a translator application to post this issue.

- [√] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [√] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [√] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
> _Specify the actual version, please don't just say "latest", tell us the version number of the mod in-game, or the name the jar had when downloading it._

Et_Futurum_Requiem-2.4.0.jar

### Describe the issue (IMPORTANT)
> _A list of steps to reproduce the issue may be helpful too. Screenshots could also prove beneficial for visual issues._

安裝了BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar就錯誤崩潰，然後刪除了BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar可以進入遊戲，但是創造新世界就錯誤崩潰。

### Mod list (OPTIONAL)
> _Crash reports contain the mod list to copy. Please use Pastebin or Gist if it is too large. If you don't have a crash report, open any world and hold F3 + C for 10 seconds to crash the game manually._

[crash-2022-10-26_13.44.57-client.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/9866519/crash-2022-10-26_13.44.57-client.txt)

[crash-2022-10-26_13.36.24-server.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/9866492/crash-2022-10-26_13.36.24-server.txt)

### Additional Context (OPTIONAL)
> _Any other info that may have been missed? If you suspect other mods to cause this issue, list them here and tell us why you suspect each of them._

**Comment by Roadhog360** [comment]
Please translate this issue.

**Comment by zxcvbnma54** [comment]
sorry I use GOOGLE to translate

Installed BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar and crashed with an error, and then deleted BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar to enter the game, but created a new world and crashed with an error.

**Comment by Roadhog360** [comment]
This error shows Biomes O'Plenty code in the stack trace, not mine. There are tons of mods which could be the cause. Have you tried only Et Futurum and Biomes O'Plenty?

**Comment by GregoriusT** [comment]
Oh no... did anyone do some mixin or asm recently? This looks like some code is being loaded out of order for some reason, and the Forge ClassLoader is an absolute mess when it comes to those things...

Yes loading a Class can sometimes seriously cause one of THOSE issues... I'm speaking from multiple experiences...

**Comment by makamys** [comment]
This looks like an EndlessIDs issue. It's supposed to add the `net.minecraft.world.chunk.Chunk.getBiomeShortArray()[S` method, but it looks like its mixin failed to get applied for some reason. Using [GasStation](https://github.com/FalsePattern/GasStation) instead of SpongeMixins might help with that.

**Comment by Roadhog360** [comment]
Questions remain unanswered, issue does not point to Et Futurum Requiem so far.
