### ISSUE TITLE
 [Question] How to make normal and specular maps work on all kinds of shulker boxes

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#197]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [ ] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
> 2.4.1

### Describe the issue (IMPORTANT)
> here are screenshot of my resource pack folder for normals and reflections, there are two versions of it for each shulker box texture
_n (normals) _s (specular) but it doesn't apply them

![123456](https://user-images.githubusercontent.com/110309314/200608040-6a95d129-b4f7-4fa7-8a0e-68a9fd64ffc3.png)
i tried to make specular and normal maps for all kinds of shulker boxes but it only applies them to vanilla boxes

However for vanilla it works, their textures work in
resourcepack.zip\assets\minecraft\textures\entity\shulker\textures of all shulkers+their maps

![2022-11-08_18 26 28](https://user-images.githubusercontent.com/110309314/200608171-3056e918-9446-41a9-a76b-78939a813eed.png)
![2022-11-08_18 27 19](https://user-images.githubusercontent.com/110309314/200608210-7f80d2c6-a606-4c27-b4e8-074c90a1f983.png)

![159485497](https://user-images.githubusercontent.com/110309314/200609995-326a2b62-ac5e-4bab-bce6-9489f2b038e9.png)

, but there are also shulkerboxes from ironshulkerbox and they don't work, I also copied the folder resourcepack.zip\assets\ironshulkerbox\textures\model\ shulker color (black in my case)\ their textures + _n, _s

![12345](https://user-images.githubusercontent.com/110309314/200607828-796d1b4d-f4bd-4688-b8d6-20cc5c1568e0.png)

![2022-11-08_18 31 13](https://user-images.githubusercontent.com/110309314/200610186-85ef51b8-35e5-4f83-87c9-0fc30ceb3842.png)

### does anyone know how to make these maps work on box textures?

**Comment by Roadhog360** [comment]
Not an issue

**Comment by kotmatross28729** [comment]
fixed by increasing texture resolution from 64x64 to 512x512
