### ISSUE TITLE
Good first 'issues'?

### ISSUE THREAD

**Issue by Richard-Rogalski** [Roadhog360/Et-Futurum-Requiem#199]
Hey! I stumbled upon this project and it looks amazing, and there are plenty of things I want to contribute and backport.

Are there any low hanging fruits y'all would like done, or should I just try adding some things I want? I know a good bit of java but have never worked on a mod before.

Also, does there happen to be a list out there with things already implemented by the mod?

**Comment by Roadhog360** [comment]
Hey, sorry I missed this. I'd be willing to talk more on the Discord server if you want! https://discord.gg/vFhf7acgMK

I do have trouble fixing some issues and I think it'd be cool to chat with you there to see if you'd be willing to help. Be sure to ping me when you see me there.

**Comment by Roadhog360** [comment]
@Richard-Rogalski
