### ISSUE TITLE
Deepslate ores incompatible with Thaumcraft's Pickaxe of the Core's abilities

### ISSUE THREAD

**Issue by SuperStormer** [Roadhog360/Et-Futurum-Requiem#212]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ x ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [ ] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)

2.4.0

### Describe the issue (IMPORTANT)

Neither of the Pickaxe of the Core's abilities work on EFR's ores.

Right-clicking a block should display ores nearby, and mining ore blocks should have a chance to drop clusters. This works on vanilla ores, but not the Deepslate variants that EFR adds (only tested on deepslate copper and deepslate gold, should apply to all though).

Screenshot of the right-click issue:
![2023-01-10_05 10 06](https://user-images.githubusercontent.com/41648788/211523004-471d008b-51f8-4fad-9b78-622f63ef8969.png)

### Mod list (OPTIONAL)
```
CodeChickenCore-1.7.10-1.1.5.jar
Et_Futurum_Requiem-2.4.0.jar
NotEnoughItems-1.7.10-2.3.20-GTNH.jar
Thaumcraft-1.7.10-4.2.3.5.jar
```
1.7.10 folder:
```
Baubles-1.7.10-1.0.1.10.jar
CodeChickenLib-1.7.10-1.1.5.6.jar
```
### Additional Context (OPTIONAL)

All mods have default configs.

**Comment by Roadhog360** [comment]
They're registered with the same ore tags as the regular version of the ore. This is likely an issue with how the Pickaxe of the Core works and there's likely nothing I can do about this. There's no difference in how the deepslate versions of ores are tagged compared to their regular counterparts.

**Comment by GregoriusT** [comment]
It happens because Et Futurum Requiem replaces all drops of Copper Ore Blocks with its own Raw Copper Ore, including its OWN Copper Ore Blocks. Yeah the Drop replacement of Copper Ores is responsible for this.

**Comment by Roadhog360** [comment]
That can't be it. Iron ore, gold ore, is also replaced and regular copper ore works fine which has the same exact drop replacement system. So if the replacement system is the culprit explain that

**Comment by GregoriusT** [comment]
The Replacer System acting upon Et Futurums OWN ore blocks is the culprit, that is LITERALLY it, it is THAT simple to explain.

Et Futurum Ore -> Drops the right thing -> Thaumcraft changes it -> Et Futurum changes it BACK with the drop replacer.

**Comment by Roadhog360** [comment]
I'm talking about the see through ores thing.

**Comment by Roadhog360** [comment]
As for the clusters, the raw ore are also registered as oreXxx in the dict. I don't feel like overcomplicating this system adding a bunch of different checks everywhere just to get around this.

**Comment by Roadhog360** [comment]
I'll look into it.

**Comment by Roadhog360** [comment]
You're right, other mod ores that are recognized by the pickaxe have an aspect according to the Thaumometer. Now the problem is I barely know anything about this mod, should deepslate get any aspects or should the deepslate versions be the same as stone?

**Comment by makamys** [comment]
Having it the same as the stone ones should be fine imo.

**Comment by GregoriusT** [comment]
Wait Thaumcraft should actually automatically register Aspects to anything "oreCopper". Did you just forget to scan the Ore Block with a Thaumometer before checking? It should only have the Terra (because Ore) and the Transmutation (because Copper) Aspect, both of which can easily be scanned without needing other progression.

---

And now for Greg going on some stupid tangent:

That said, I had to deal with a LOOOOT of inefficiencies in Thaumcrafts Aspect API in GT6, and I would not be surprised if it somehow failed to see your Copper Ore in the OreDict.

Luckily this is not a serious Issue, it's just an Issue of making things work nicely, so that people stop complaining about minor inconsistencies. XD

You can get all important Thaumcraft Aspects from Vanilla Blocks. The Creeperface Sandstone Block even gives Ordo of all things...

**Comment by SuperStormer** [comment]
> Wait Thaumcraft should actually automatically register Aspects to anything "oreCopper". Did you just forget to scan the Ore Block with a Thaumometer before checking? It should only have the Terra (because Ore) and the Transmutation (because Copper) Aspect, both of which can easily be scanned without needing other progression.
> 
I did - it had no aspects.

**Comment by makamys** [comment]
I added aspects for the deepslate copper and it gets highlighted by the pickaxe now.

Copper ore had `[2 Metallum, 1 Terra, 1 Permutatio]` auto-generated by Thaumcraft, but for some reason deepslate copper ore had nothing, even though they're both registered as `oreCopper` in the ore dict.

**Comment by Roadhog360** [comment]
I wonder if it's because of when they are being registered.

**Comment by GregoriusT** [comment]
Oh right I forgot about the Metallum Aspect, because literally all Metal Ingots have it XD
