### ISSUE TITLE
Missing Thaumcraft Aspects

### ISSUE THREAD

**Issue by SuperStormer** [Roadhog360/Et-Futurum-Requiem#213]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [ ] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)

2.4.0

### Describe the issue (IMPORTANT)

Some items are missing TC aspects.

For example:
- new doors
- all deepslate ores
- nether gold ore
- boats
- ancient debris, netherite scrap
- purpur blocks
- armor stands
- smooth quartz and sandstone
- cornflower, lily of the valley, wither rose, sweet berries
- amethyst shards and blocks
- tinted glass
- shulker shells and boxes
### Mod list (OPTIONAL)
```
CodeChickenCore-1.7.10-1.1.5.jar
Et_Futurum_Requiem-2.4.0.jar
NotEnoughItems-1.7.10-2.3.20-GTNH.jar
Thaumcraft-1.7.10-4.2.3.5.jar
```
1.7.10 folder:
```
Baubles-1.7.10-1.0.1.10.jar
CodeChickenLib-1.7.10-1.1.5.6.jar
```
### Additional Context (OPTIONAL)

All mods have default configs.

**Comment by Roadhog360** [comment]
I don't really know about Thaumcraft aspects or what I'm supposed to give them. I barely know about the mod, so nothing after the original Et Futurum 1.5.5 ended up getting aspects, and likely will not, sorry.

**Comment by SuperStormer** [comment]
For doors, ores and boats, you could copy the values from the vanilla equivalents.
