### ISSUE TITLE
reversed protection values for Netherite Leggings and Netherite chestplate

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#218]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [x] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
> 2.4.2

### Describe the issue (IMPORTANT)
In vanilla, for example, diamond leggings have "protection" 6, 

![Desktop Screenshot 2023 01 16 - 19 46 16 68](https://user-images.githubusercontent.com/110309314/212731267-f74c944f-5131-4dbb-94c1-f1f3027a29b9.png)

and diamond chestplate "protection" 8,
![Desktop Screenshot 2023 01 16 - 19 46 15 11](https://user-images.githubusercontent.com/110309314/212731291-d112d377-f160-471a-bbea-0a5e2ee8cd1b.png)

 in et futurum requiem these values are reversed, so netherite leggings are better than netherite chestplate

![Desktop Screenshot 2023 01 16 - 19 46 19 63](https://user-images.githubusercontent.com/110309314/212731321-70c1790a-60f9-4269-81a4-94f43cf2fd68.png)

![Desktop Screenshot 2023 01 16 - 19 46 18 30](https://user-images.githubusercontent.com/110309314/212731343-95795de5-08b7-4e83-a6fa-87c747c66a62.png)

**Comment by makamys** [comment]
Fixed as of 3af52d0. (The values can also be changed in the config now.)
