### ISSUE TITLE
Incompatibility with bspkrsCore's title screen mobs rendering

### ISSUE THREAD

**Issue by ENDERZOMBI102** [Roadhog360/Et-Futurum-Requiem#220]
### Please check any boxes that apply to you and your issue
- [ ] I use a translator application to post this issue.
- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.
- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.
- [x] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem
2.4.2-nomixin

### Describe the issue
Start the game with bspkrsCore's title screen mobs enabled and et futurum requiem

attached the stack trace and and the related parts of the log: [error.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/10445215/error.log)

### Explaination
It seems that Et Futurum Requirem did not account for player renderers outside of an in-world context, which are rare yes, but do exist, it should do a check for whether we are playing or not, as this can cause issues.

**Comment by Roadhog360** [comment]
Fixed in [989341e](https://github.com/Roadhog360/Et-Futurum-Requiem/commit/989341e83fb062ec50050cd506699c7701e3e5e8).
![image](https://user-images.githubusercontent.com/11903511/213880948-ab679571-60bd-40d8-b775-794911f87a11.png)
