### ISSUE TITLE
Spectator mode crashes with Ars Magica 2

### ISSUE THREAD

**Issue by DrParadox7** [Roadhog360/Et-Futurum-Requiem#221]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [ ] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
> _Specify the actual version, please don't just say "latest", tell us the version number of the mod in-game, or the name the jar had when downloading it._

The latest latest version, idk.
_I haven't updated to the latest yet but we are at version 2.4.0._

### Describe the issue (IMPORTANT)
> _A list of steps to reproduce the issue may be helpful too. Screenshots could also prove beneficial for visual issues._

isSpectator is being applied to non-player entities causing crashes.
In this case it is being applied to a Zone Spell from Ars Magica 2 when a Fire Elemental is summoned.

[crash-2023-01-18_17.05.59-server.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/10449077/crash-2023-01-18_17.05.59-server.txt)

### Mod list (OPTIONAL)
> _Crash reports contain the mod list to copy. Please use Pastebin or Gist if it is too large. If you don't have a crash report, open any world and hold F3 + C for 10 seconds to crash the game manually._

[The Lost Era Modpack
](https://modrinth.com/modpack/the-lost-era/)

### Additional Context (OPTIONAL)
> _Any other info that may have been missed? If you suspect other mods to cause this issue, list them here and tell us why you suspect each of them._

**Comment by makamys** [comment]
Seems to be fixed already (see 03a24cfbb15028ee9d793ed0a818235e62bf2b71)

**Comment by Roadhog360** [comment]
Please update before making bug reports
