### ISSUE TITLE
(smithing table) shift + right mouse button distributes items incorrectly + "ghost items?"

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#226]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [x] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
>2.4.2 latest commit

#### when you press shift and right mouse button, diamond items go into the slot for the ingot, and the ingot into the slot for the item

https://user-images.githubusercontent.com/110309314/213861554-cdb9d927-e0e8-43b3-a282-09153796c5d4.mp4

### "ghost items":

https://user-images.githubusercontent.com/110309314/213861675-a74c0525-3728-4e3d-8ce6-fcad741638f9.mp4

**Comment by Omgise** [comment]
Anvil has the same problem

**Comment by Roadhog360** [comment]
I can't reproduce the ghost items issue. Another mod may be causing that one, can you tell me if you still get it in vanilla+Et Futurum Requiem?

**Comment by Omgise** [comment]
> I can't reproduce the ghost items issue. Another mod may be causing that one, can you tell me if you still get it in vanilla+Et Futurum Requiem?

Anvil error in vanilla (The Et Futurum Requiem is not installed)


https://user-images.githubusercontent.com/106000018/213952470-93fcf202-e971-4cb7-95eb-b8422173e925.mp4

**Comment by Roadhog360** [comment]
I am aware of the shift click issue, I am talking about the ghost items issue.

**Comment by GregoriusT** [comment]
Short Question, is a dedicated Server involved? Ghost Items tend to happen when the Server does a GUI thing but the Client does not.

**Comment by Roadhog360** [comment]
I tried it on a server and I still could not reproduce the issue.

**Comment by Roadhog360** [comment]
The ghost items are possibly caused by another mod. Are you able to reproduce the issue with just vanilla and Et Futurum Requiem?

**Comment by kotmatross28729** [comment]
> The ghost items are possibly caused by another mod. Are you able to reproduce the issue with just vanilla and Et Futurum Requiem?

(sorry for the long answer)
yes, you're right, the "ghost items" bug is due by  CoFHCore
