### ISSUE TITLE
Installing CoFH Core with lwjgl3ify installed crashes

### ISSUE THREAD

**Issue by sousuke0422** [Roadhog360/Et-Futurum-Requiem#228]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [ ] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)

- 2.4.2+nomixin

### Describe the issue (IMPORTANT)
- Installing CoFH Core in the location where [lwjgl3ify](https://github.com/GTNewHorizons/lwjgl3ify) is installed crashes after startup and before the screen appears.
- Before installing CoFH Core I made sure it worked with java 17. (Except for spectator mode)

### Mod list (OPTIONAL)

- CoFHCore-[1.7.10]3.1.4-329
- CoFHLib-[1.7.10]1.2.1-185
- Et_Futurum_Requiem-2.4.2-nomixin
- gtnhmixins-2.1.11
- lwjgl3ify-1.1.13

### Additional Context (OPTIONAL)
- [log](https://mclo.gs/243kK9m)

**Comment by makamys** [comment]
Try adding [Mixingasm](https://github.com/makamys/Mixingasm).

**Comment by sousuke0422** [comment]
Thank you. It worked.
