### ISSUE TITLE
Server crashes when elytra are enabled

### ISSUE THREAD

**Issue by kang-png** [Roadhog360/Et-Futurum-Requiem#229]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [ ] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
> _Specify the actual version, please don't just say "latest", tell us the version number of the mod in-game, or the name the jar had when downloading it._
Et_Futurum_Requiem-2.4.2

### Describe the issue (IMPORTANT)
> _A list of steps to reproduce the issue may be helpful too. Screenshots could also prove beneficial for visual issues._

### Mod list (OPTIONAL)
> _Crash reports contain the mod list to copy. Please use Pastebin or Gist if it is too large. If you don't have a crash report, open any world and hold F3 + C for 10 seconds to crash the game manually._
Et_Futurum_Requiem-2.4.2.jar
worldedit-forge-6.1.1-dist.jar
AsyncWorldEditInjector.jar

### Additional Context (OPTIONAL)
> _Any other info that may have been missed? If you suspect other mods to cause this issue, list them here and tell us why you suspect each of them._
log：https://pastebin.com/gSbXpYNp
crash：https://pastebin.com/r1TXmBMU

When I disable this, the mod loads normally
`    # Enables the elytra item.
    # Modified Classes: net.minecraft.entity.EntityLivingBase net.minecraft.entity.player.EntityPlayer net.minecraft.entity.EntityTrackerEntry net.minecraft.network.NetHandlerPlayServer net.minecraft.client.entity.AbstractClientPlayer net.minecraft.client.entity.EntityPlayerSP net.minecraft.client.model.ModelBiped net.minecraft.client.renderer.entity.RenderPlayer [default: true]
    B:enableElytra=false`

Server cores used：
https://private.yxsjmc.cn/%E4%B8%93%E7%94%A8%E8%B5%84%E6%BA%90/%E9%83%A8%E7%BD%B2%E5%8C%85/%5B%E9%83%A8%E7%BD%B2%E5%8C%85%5DUranium1.7.10%5B%E4%BD%BF%E7%94%A8Java8%5D.tar.gz

**Comment by GregoriusT** [comment]
@Roadhog360 the Error should be in the following Line, since the Code does not line up according to the Exception in those Logs.

https://github.com/Roadhog360/Et-Futurum-Requiem/blob/master/src/main/java/ganymedes01/etfuturum/core/handlers/ServerEventHandler.java#L1677

`ws.getEntityTracker().trackedEntities`

if getEntityTracker() can return null, this will fail with a NullPointerException.

**Comment by makamys** [comment]
I thought it was this line - this is line 1250 in the 2.4.2 version of the source code.
https://github.com/Roadhog360/Et-Futurum-Requiem/blob/eee8a990b87c0db59e158633fbe06bcf3982982d/src/main/java/ganymedes01/etfuturum/core/handlers/ServerEventHandler.java#L1250
Which would mean `ete` is null, which is possible if `ws.getEntityTracker().trackedEntities` (a HashSet) contains a null element. But vanilla code doesn't do null checking when iterating over the elements of the set either, so in this case a crash should happen somewhere else even if it wasn't for EFR.

As for your explanation, it doesn't add up either. `getEntityTracker()` returns the value of a final field which is initialized to something in `WorldServer`'s constructor, meaning it should never be null. Uranium is probably doing something weird.

**Comment by GregoriusT** [comment]
Oh you got the Link that actually lines up properly, in which case ete is indeed null, no amount of "denial" can change that. So better add a null check there, or a "remove(null);" aimed at the HashSet to prevent further Issues elsewhere too.

---

And does Vanilla really not do any null checking? Even an instanceof is a null check. Or something in EFR is adding a null to it? I dont actually know, I only hypothesize there.

**Comment by makamys** [comment]
> And does Vanilla really not do any null checking?

Yep, see `EntityTracker#updateTrackedEntities` for example.

**Comment by Roadhog360** [comment]
Any updates on this?

**Comment by GregoriusT** [comment]
I would suggest just adding a null check and if someone comes by with a real update on this issue, we can find the problem later. Better than just randomly crashing anyone for no reason, since that causes more damage than not knowing the source of the issue. The damage being that people disable the elytra on their servers, and their end users being left without a feature they hoped they would have, which is far worse than a mystery crash.

**Comment by Roadhog360** [comment]
I need to reproduce this before I can guarantee that is the issue. As previously pointed out, vanilla does not do any null checks. I don't think lists can even contain a null value.

**Comment by kang-png** [comment]
uranium has some code for "compatible plugins to register forge events", the attached file
 is a comparison of two forge+bukki hybrid server cores
[报告.pdf](https://github.com/Roadhog360/Et-Futurum-Requiem/files/11512328/default.pdf)
https://github.com/UraniumMC/Uranium/blob/f73a12f22bda26b7db8bf2c80258c63767b272aa/patches/cpw/mods/fml/common/eventhandler/ASMEventHandler.java.patch#LL2C5-L2C8

**Comment by Roadhog360** [comment]
I had not noticed this was on a Bukkit hybrid server. Those are unfortunately not supported because they break too easily.

**Comment by GregoriusT** [comment]
Ah that explains it!

Would still be nice if there was a basic null check though, those are practically free in java and dont hurt. As a bonus, people will be less likely to report this Bug over and over and over again, wasting your time. ;)

**Comment by GregoriusT** [comment]
Lists IN GENERAL can contain a LOT of null values if such are added to them. There is no inherent protection against them. You should at least TRY to support these cases, especially when it is easy to make them not happen, because what if this was an optimization they did to vanilla code because removing elements from a list is more expensive than checking for a null? This is why just adding a null check is a good idea overall.

**Comment by Roadhog360** [comment]
It's not that I believe it's expensive, I just don't like the way unnecessary checks look

**Comment by GregoriusT** [comment]
luckily that check is necessary for Compat, so you dont need to worry about that. :P
