### ISSUE TITLE
Cauldron doesn't work like vanilla

### ISSUE THREAD

**Issue by Starexify** [Roadhog360/Et-Futurum-Requiem#233]
- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem
2.4.3

### Describe the issue
Can't take the water/lava out with the bucket out a cauldron,

### Additional Context
I can only do potions and take the water out with a bottle.

**Comment by Roadhog360** [comment]
This is a suggestion.

**Comment by GregoriusT** [comment]
Dumb Question, can you fill the Cauldron with Lava in the first place? And same for Powder Snow? (in EFR i mean ofcourse)

As for taking out the Water Bucket, isn't that already possible? Don't have MC open to confirm atm.

---

Random-AF Side Note: I hate how closing an Issue on GitHub has this passive aggressive "closed as not planned" wording for if something doesn't fit any other category like fixed or completed. It often gives the wrong impression to whoever opened an issue... But that is a GitHub complaint not a Project related one.

**Comment by Starexify** [comment]
About the Water Bucket, no I can't take out the lava/water out a Cauldron with buckets only the water with bottles. Normally you can do it and should be able to. I think I may mistook the mod with another backporting mod, but I will find the mod that does that, if it's from EtFuturum i'll let you know.

**Comment by Starexify** [comment]
I tried only with Et Futurum, and the lava cauldron does exist in Et Futurum, but I still can't use a bucket to get the lava/water out of it... I'll make an suggestion then.

**Comment by Roadhog360** [comment]
Yes, this is a suggestion. You cannot remove water from cauldrons in vanilla using a bucket.

**Comment by GregoriusT** [comment]
Clarification, he means in vanilla 1.7.10. Later MC Versions do allow for Bucket use on Cauldron for extraction of contents. ;)

**Comment by Roadhog360** [comment]
Becausw it's a feature request not a bug report

@fluid-decanter
