### ISSUE TITLE
Server crash when using Thaumic Tinkerer's Dynamism Tablet

### ISSUE THREAD

**Issue by krallendertoten** [Roadhog360/Et-Futurum-Requiem#234]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ X] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

https://pastebin.com/NRC1PgrH

- [ X] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

2.4.3

### Describe the issue (IMPORTANT)

When trying to get a Dynamism Tablet from Thaumic Tinkerer to break a block or use any item in a server, it instantly causes a crash. This does not happen in singleplayer. 
The stacktrace always mentions EtFuturum; however, this might be outside the scope of your mod, but I wanted to bring it to your attention just in case.

**Comment by Roadhog360** [comment]
How do I use this tablet?

**Comment by krallendertoten** [comment]
You place it down, it has a little circle icon to show its facing direction, place a block or tank or something in front of it, then put an item into the tablet and click the button in the interface according to the expected use (right click if you put down some sort of tank/cauldron in front and a bucket in the tablet, left click if you put a block of cobble in front and a pickaxe in the tablet). I've had it crash with both left and right clicks, but only in a server

**Comment by Roadhog360** [comment]
Thank you.
