### ISSUE TITLE
spectator mode does not work in EFR 90e42ac

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#235]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

Et Futurum Requiem 2.4.2 SNAPSHOT 90e42ac

### Describe the issue (IMPORTANT)

In version 2.4.3 the spectator mode worked, but in the latest build of ci I just can't pass through blocks

90e42ac :

https://user-images.githubusercontent.com/110309314/219868738-7bdd824d-aa25-4c7d-ac34-f2ad94a6b863.mp4

2.4.3 :

https://user-images.githubusercontent.com/110309314/219868741-3c87a458-47e8-451d-89fc-ec2052f935aa.mp4

**Comment by GregoriusT** [comment]
Wait the most recent change to fix a crash with Spectator Mode ON/OFF checks has caused this?! Was there a muted exception or something in the Code that now instead returns that the Player doesn't have Spectator Mode? Or is this yet another Client Server Issue, just in Singleplayer this time?

**Comment by Roadhog360** [comment]
I'm looking at the code and I am confused. It should return the same stuff but somehow the server no longer recognizes the player is in spectator mode. Why does shit like this happen....

**Comment by GregoriusT** [comment]
Uh okay your change makes sense from a performance standpoint but uhh, we definitely need to wait for them to compile and test it themselves because I do not think that could possibly fix it, right? That said you never know cryptic Minecraft garbo.
