### ISSUE TITLE
Slightly wrong subtitles (probably sounds)

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#240]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
Et_Futurum_Requiem-2.4.4-SNAPSHOT-dbaea20

### Describe the issue (IMPORTANT)

if the cauldron is filled with water, then when scooping water out of it with a glass bottle, `subtitle.item.bottle.fill` is written in the subtitles (which is correct)
but when filling the cauldron with a potion, the subtitles also write `subtitle.item.bottle.fill` (which is not correct) and when scooping from there with a glass bottle, the subtitles write `subtitle.item.bottle.empty`, although it should be the other way around

### fill - fill (correct)
![Desktop Screenshot 2023 02 19 - 23 06 11 29](https://user-images.githubusercontent.com/110309314/219972640-7b2a866c-2559-4491-b60f-ed09faeac1f1.png)

### empty - fill (wrong, should be empty)
![Desktop Screenshot 2023 02 19 - 23 06 19 45](https://user-images.githubusercontent.com/110309314/219972684-9433afa7-2ab0-4dda-8b92-dc71b691dc14.png)

### fill - empty (wrong, should be fill )
![Desktop Screenshot 2023 02 19 - 23 06 31 29](https://user-images.githubusercontent.com/110309314/219972686-266e1d32-c7f3-4d4f-80a8-2d88ca260925.png)

it should be:
subtitle.item.bottle.empty - should be written when pouring into cauldron
subtitle.item.bottle.fill - should be  write when filling a glass bottle with a potion

and also a sea lantern, when placed, makes the sound of steps
![Desktop Screenshot 2023 02 19 - 23 05 40 65](https://user-images.githubusercontent.com/110309314/219972703-1d1c2df0-8aa2-4cab-8f32-00a035161d3b.png)

#### I think this is due to the fact that some things use the wrong sounds, so the subtitles are written as it is

**Comment by Roadhog360** [comment]
Sound events in 1.7.10 are primitive and often recycle sounds or use sounds. All we can do is make the subtitle use the sound name as the key, so some blocks that use footstep sounds will simply have that as the subtitle. This cannot be fixed. What you see is what you get.
