### ISSUE TITLE
[Vanilla Bug] Chiseled Sandstone generates in Mesa instead of Red Sandstone

### ISSUE THREAD

**Issue by DarkBumus** [Roadhog360/Et-Futurum-Requiem#245]
The title pretty much says it all: At some places, especially near cave entrances, the vanilla code will generate Chiseled Sandstone, instead of the Red Sandstone (since that wasn't available in 1.7.10 yet]
![2023-02-22_21 22 56](https://user-images.githubusercontent.com/126115769/220758122-30b506f0-36e3-4e0d-93d4-3701eec56666.png)

**Comment by Roadhog360** [comment]
Please use the template next time btw

**Comment by Roadhog360** [comment]
Is this screenshot even taken in 1.7.10? I cannot reproduce this at all. I looked at MC-55228 and its duplicates, going to every seed and coordinate and there was no chiseled sandstone, only regular sandstone.

I strongly remember this being a bug in 1.7.10 though, but I simply cannot find any chiseled sandstone, it just is red sand.

**Comment by GregoriusT** [comment]
Is the Cave generator setting Sand Blocks to Sandstone whenever it is carving? And does it just keep the Metadata? Because Sand Metadata is 1 for Red Sand and Chiseled Sandstone is Metadata 1 too, so this MIGHT be absolutely unrelated to Et Futurum at all whatsoever.

**Comment by Roadhog360** [comment]
That is why it's labeled vanilla bug. I told him to put it here because I wanted to fix it in EFR anyways

**Comment by Roadhog360** [comment]
After further code analysis I have determined this doesn't happen in vanilla 1.7.10. I'm not even sure how this picture was taken, and as for myself I guess I mandela'd myself into believing this bug was in the game, but I checked tons of mesa cave entrances and NONE of them had any sort of sandstone, it's just red sand that floats.
