### ISSUE TITLE
Crash when make a world , when asjcore + mobstacker +et futurum requiem is installed

### ISSUE THREAD

**Issue by quentin452** [Roadhog360/Et-Futurum-Requiem#246]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

[crash-2023-02-24_00.24.50-server.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/10819322/crash-2023-02-24_00.24.50-server.txt)

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

2.4.3

### Describe the issue (IMPORTANT)

When i make a world ,i get instant crash.

### Mod list (OPTIONAL)

* Et_Futurum_Requiem-2.4.3
* 1.7.10-ASJCore-1.2.1.2
* MobStacker-1

**Comment by Roadhog360** [comment]
Multiple incompatibilities with ASJCore are being tracked on #216. ASJCore appears to do multiple things which are not compatible with Et Futurum Requiem so I just keep it all there.
