### ISSUE TITLE
[10:39:22] [Client thread/ERROR]: Error loading recipe:  java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by zxcvbnma54** [Roadhog360/Et-Futurum-Requiem#247]
使用NEI查看用途出錯
查看銅的配方用途會出錯

Using NEI to check the usage error
Going wrong when looking at recipe uses for copper

[crash-2023-02-25_10.39.23-client.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/10830104/crash-2023-02-25_10.39.23-client.txt)

**Comment by Roadhog360** [comment]
Issue does not use issue template

**Comment by GregoriusT** [comment]
Additionally the Crash Log is a completely different Error which has already been fixed. Please provide the correct crash log that actually contains the Index Out of Bounds.
