### ISSUE TITLE
View copper and crafting recipes with NEI, crashes

### ISSUE THREAD

**Issue by zxcvbnma54** [Roadhog360/Et-Futurum-Requiem#248]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
Et_Futurum_Requiem-2.4.3
### Describe the issue (IMPORTANT)

使用NEI查看銅得合成用途崩潰
NEI 
copper synthesis use
collapse

### Mod list (OPTIONAL)

mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
etfuturum{2.4.3} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.4.3.jar) 

### Additional Context (OPTIONAL)

google translate

**Comment by GregoriusT** [comment]
Please provide Logs of the Crash, otherwise we wont know what you are talking about.

**Comment by zxcvbnma54** [comment]
ok 
[crash-2023-02-25_12.09.32-client.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/10830208/crash-2023-02-25_12.09.32-client.txt)

**Comment by GregoriusT** [comment]
That one was fixed already, unsure if the update is out already, but if you compile it yourself it should work just fine.

**Comment by zxcvbnma54** [comment]
我不知道，我用NEI案U鍵，對銅錠使用用途就，崩潰
不知道如何修復

I don't know, I use the U key of the NEI case, and it crashes when I use it for copper ingots
don't know how to fix     (google translate)

**Comment by Roadhog360** [comment]
This could possibly be unrelated, but as I cannot reproduce the crash and wasn't able to reproduce the original crash I'm not sure.

**Comment by GregoriusT** [comment]
Have you looked at the Crash Log in Detail? It crashed when displaying Shulker Upgrade with Metadata 1, which is the Copper Shulker Upgrade.

**Comment by Roadhog360** [comment]
I'll admit I skimmed it lol
Then this is the same issue, you are absolutely right.

**Comment by zxcvbnma54** [comment]
謝謝！我解決了，崩潰

Thanks! I solved it, crash
