### ISSUE TITLE
random crash during world generation

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#255]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

 a90e901

### Crash report
https://pastebin.com/iqEW0yry

**Comment by Roadhog360** [comment]
Thanks for the report
