### ISSUE TITLE
Incompatibility with Gilded Games Util

### ISSUE THREAD

**Issue by Lundashy** [Roadhog360/Et-Futurum-Requiem#256]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

Et Futurum Requiem 2.4.3

### Describe the issue (IMPORTANT)

After installing the "Gilded Games Util" mod I get a lighting error when you break the blocks, (here is a video where you can see the problem I have)       https://www.youtube.com/watch?v=Lg0WtTbU7eQ

In old versions of the mod (Et Futurum Requiem 2.3.1) this error did not happen.
Gilded Games Util is a mandatory complement to be able to use the "The Aether II" mod, here is the link of the mod that I want to use:

Gilded Games Util:    https://www.curseforge.com/minecraft/mc-mods/gilded-games-util
The Aether II :   https://www.curseforge.com/minecraft/mc-mods/aether-ii
![2023-04-06_19 05 47](https://user-images.githubusercontent.com/108596963/230503410-28d54c71-4e61-4c8e-8a5b-1aa49da35599.png)

### Mod list (OPTIONAL)

UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAAAAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAAAAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJAAAAAAAAA	etfuturum{2.4.3} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.4.3.jar) 

### Additional Context (OPTIONAL)

Possibly it is the "Threaded Lighting" that is incorporated into the "Gilded Games Util" mod.
I suspect that because the name is related to the lighting error that I have.

Thank you very much for reading, have a nice day ^^

**Comment by GregoriusT** [comment]
Quick question, did you move away from the spawn area and test it there? This looks like you are in the small zone where you cant break blocks, and this is the resulting lighting issue. I can be way off with that guess though.

**Comment by DarianLStephens** [comment]
Are they using the version of Gilded Games Util which had threaded lighting stripped? That probably won't have this problem.

**Comment by Roadhog360** [comment]
I am not sure if my mod is the source of this issue. Does the same issue happen without it?

**Comment by Lundashy** [comment]
> Quick question, did you move away from the spawn area and test it there? This looks like you are in the small zone where you cant break blocks, and this is the resulting lighting issue. I can be way off with that guess though.

No, I tested it near the spawn point, this error only appears in the overworld, (at the end and in the Nether this does not happen)
Here is a video so you can see it better:     https://www.youtube.com/watch?v=lMYkz0gSwxM

**Comment by Lundashy** [comment]
> Are they using the version of Gilded Games Util which had threaded lighting stripped? That probably won't have this problem.

I am using this version of Gilded Games Util
https://www.curseforge.com/minecraft/mc-mods/gilded-games-util
[Gilded Games Util 1.7.10-1.3.2]

**Comment by Lundashy** [comment]
Thank you all very much for helping me solve this problem ^^

**Comment by Roadhog360** [comment]
EFR may be doing something it is not supposed to if it breaks this older version of that threaded lighting mod. I will leave this open and investigate for now.

**Comment by Roadhog360** [comment]
I finally got around to testing and I can't even say whether or not threaded lighting is entirely stable. After installing it, my world chunk loading gets exponentially slower as I load new chunks, and I also eventually experience the lighting glitches you describe. I can't really say what causes it.

**Comment by embeddedt** [comment]
Threaded lighting is not at all stable.

**Comment by Roadhog360** [comment]
Should I close this then?

**Comment by embeddedt** [comment]
Yes. There are better alternatives if lighting is causing lag ([shameless plug](https://github.com/embeddedt/ArchaicFix)).
