### ISSUE TITLE
Et Futurm Crashes On Start Up.

### ISSUE THREAD

**Issue by toErIpNid** [Roadhog360/Et-Futurum-Requiem#258]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [X] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
2.4.3

### Describe the issue (IMPORTANT)
Et Futurm causes the game to crash on start up when used with some other mods. The log looks like jargon to me, so I'm not sure if I need to change potion IDs or similar.

Log: https://pastebin.com/SqeE188A

### Mod list (OPTIONAL)
![modlist](https://user-images.githubusercontent.com/78389307/232224576-0885830d-fbe8-4677-9af6-c65eaaaa70d1.PNG)

1.7.10 Folder contains Baubles and CodeChickenCore.

**Comment by GregoriusT** [comment]
Note: This is a Classloader Issue, so probably a mixin/asm related thing.

**Comment by Roadhog360** [comment]
I've never heard of a lot of these mods, would you mind narrowing down the cause please?

**Comment by toErIpNid** [comment]
I have no idea what the cause could be personally. 

About half of the mod list are just Thaumcraft addons, which are notorious for causing enchantment/potion ID issues with each other and other mods if it helps.

**Comment by Roadhog360** [comment]
What I meant is continuing to remove mods until you find the culprit.

**Comment by embeddedt** [comment]
Try installing [UniMixins](https://github.com/LegacyModdingMC/UniMixins/releases/tag/0.1.6) and using the `nomixin` variant of EFR.

**Comment by toErIpNid** [comment]
> Try installing [UniMixins](https://github.com/LegacyModdingMC/UniMixins/releases/tag/0.1.6) and using the `nomixin` variant of EFR.

I tried doing what embeddedt wanted to no avail. Here's the developements:
![bruhbro](https://user-images.githubusercontent.com/78389307/232248783-9d08af01-3546-4020-93a7-4d97a878b4bb.PNG)

Latest Log: https://pastebin.com/5iPUryQZ

Should I still do a binary search?

**Comment by makamys** [comment]
It looks like you have two mods that try to expand the potion ID limit at the same time (EIDE and some mystery mod), though your log is missing a lot of information. EIDE supposedly has an option to disable potion extension, so you could try disabling that.

By the way, is this the most detailed log the Curse launcher gives you? In that case you could copy the instance to a MultiMC-based launcher and run it there to obtain a more verbose log (`fml-client-latest.log`) that tells you which mod printed what line.

**Comment by toErIpNid** [comment]
> It looks like you have two mods that try to expand the potion ID limit at the same time (EIDE and some mystery mod (probably Ars Magica)), though your log is missing a lot of information. EIDE supposedly has an option to disable potion extension, so you could try disabling that.
> 
> By the way, is this the most detailed log the Curse launcher gives you? In that case you could copy the instance to a MultiMC-based launcher and run it there to obtain a more verbose log (`fml-client-latest.log`) that tells you which mod printed what line.

Okay, I figured it out. It's either E ID E or Not Enough IDs (or maybe both), as when those are disabled the game now boots up completely and you can play it fine. 

And yes that's the best log curseforge gives you.

**Comment by Roadhog360** [comment]
Oh I didn't even notice that. Yes, other ID extenders are made redundant because of NEIDs
