### ISSUE TITLE
Crash on Startup - Enchanting Related?

### ISSUE THREAD

**Issue by Shahelion** [Roadhog360/Et-Futurum-Requiem#259]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
2.4.4

### Describe the issue (IMPORTANT)
The game crashes during loading. Does not reach the main menu.

### Mod list (OPTIONAL)
https://gist.github.com/Shahelion/8101484f1bb73776a1d9df2b4889e5fd

### Additional Context (OPTIONAL)
Disabling all three enchantments prevents the crash.

**Comment by Roadhog360** [comment]
This is absolutely a mod conflict.
Have you tried removing batches of mods to narrow down the issue, and verifying that it is it indeed not happening when EFR is not present?

**Comment by makamys** [comment]
A full `fml-client-latest.log` would be helpful.

**Comment by Roadhog360** [comment]
What is actually the difference between a normal latest.log and that?

**Comment by GregoriusT** [comment]
latest.log does not contain any useful information (because its just the server console output basically), fml-client-latest contains all the useful stuff.

**Comment by makamys** [comment]
It's also worth noting that the name and content of log files differs subtly from launcher to launcher. But OP is using MultiMC so it should be like Greg says (`fml-client-latest.log` containing Forge and mod messages with full verbosity, `latest.log` mostly just containing server messages).

**Comment by Roadhog360** [comment]
@Shahelion Do you have an fml-client-latest.log?

**Comment by Shahelion** [comment]
https://gist.github.com/Shahelion/a8e94bc432b2667cdaeaf5897898f0da

**Comment by makamys** [comment]
This is not `fml-client-latest.log`, you can find that in the `.minecraft/logs` directory (and you can get to `.minecraft` by clicking on the *"Open .minecraft"* button in the *"Version"* tab of MultiMC.)

Anyway, try adding [UniMixins](https://github.com/LegacyModdingMC/UniMixins/releases). Not sure if this will fix it, but it's always worth a try.

**Comment by Shahelion** [comment]
[fml-client-latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/11317374/fml-client-latest.log)

**Comment by Roadhog360** [comment]
@Shahelion Have you attempted the previous suggestions as well? (Removing batches of mods to find which mod or mods are conflicting, using [UniMixins](https://github.com/LegacyModdingMC/UniMixins/releases)?)

**Comment by makamys** [comment]
If you remove mods, I'd recommend starting with DragonAPI and Ars Magica, they look like the most likely culprits based on the log.

**Comment by Roadhog360** [comment]
Any updates?

**Comment by Roadhog360** [comment]
Question has gone unanswered for several months, closing for now
If the OP replies with more info we can reopen this
