### ISSUE TITLE
freeze on using enchantment table

### ISSUE THREAD

**Issue by xenoramos** [Roadhog360/Et-Futurum-Requiem#263]
After updating to 2.4.4 (from 2.4.2) I can't reliably use enchantment table. Sometimes when I hover mouse to see preview of enchantment client just freezes and sometimes I can see preview normally, but if I click to enchant, it freezes as well and this time some sound start playing infinitely. That is not 100% case, so I'm guessing it has to do with some specific enchantment. That is not an ID conflict, as I checked it with "anti ID conflicts" mod.
Here's both logs
[fml-client-latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/11308342/fml-client-latest.log)
[latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/11308349/latest.log)

As I mentioned, I used to play on that modpack with Et Futurum Requiem 2.4.2, and it all worked perfectly, without any issues, on same config files.

p.s. I couldn't find where the template mentioned in "READ BEFORE OPENING AN ISSUE!" is located. If you could point me into it directly - I would gladly use it.

**Comment by Roadhog360** [comment]
The template is in the button where you open an issue

**Comment by GregoriusT** [comment]
How about instead of passive-aggressively closing an Issue for "not adhering enough to the template" despite the poster clearly having given all necessary information. You look into the Logs to see that DivineRPG is having Tooltip Issues, and ask to uninstall that specific Mod to see if that fixes the Issue?

**Comment by Roadhog360** [comment]
He asked where the template is, so I pointed it to him.
