### ISSUE TITLE
Game freezes on using enchantment table

### ISSUE THREAD

**Issue by xenoramos** [Roadhog360/Et-Futurum-Requiem#264]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
2.4.4

### Describe the issue (IMPORTANT)
Using the enchantment table freezes client sometimes. Either when hover mouse to preview enchantment, or when applying enchantment.

### Mod list (OPTIONAL)
https://pastebin.com/HMq2iWKw
(under 1.7.10 folder are following mods not included in log)
-bspkrsCore-universal-6.16
-Baubles-1.7.10-1.0.1.10
-CodeChickenLib-1.7.10-1.1.3.138-universal
-ForgeMultipart-1.7.10-1.2.0.345-universal
-LibSandstone-1.0.0

### Additional Context (OPTIONAL)
I have tried reproducing crash on same modpack, but on newly made world, it works fine, no matter how much times I try to enchant
Issue appears only when I play on my old world, usually freezes on second to third enchant attempt.
On previously installed 2.4.2 version everything was working great, without freezes or crashes.

And here's newly made logs just in case, right after the issue (had to kill minecraft via task manager because it freezes infinitely)

[fml-client-latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/11309888/fml-client-latest.log)
[latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/11309890/latest.log)

**Comment by GregoriusT** [comment]
As I hinted at before, try removing DivineRPG, just as a test to see if it still does that.

**Comment by xenoramos** [comment]
> As I hinted at before, try removing DivineRPG, just as a test to see if it still does that.

Tried it, didn't change anything in that issue, still got a freeze after enchanting a regular iron pickaxe. And the odd sound effect... something between ambient or machine'ish sound started when game got frozen.

**Comment by GregoriusT** [comment]
Can you try using NEIs cheaty Enchanting Menu? Just to make sure it is the EFR GUI and not the enchanted output. ;)

**Comment by Roadhog360** [comment]
Looking at my GUI code, I think I may be able to see where this is coming from actually.

**Comment by Roadhog360** [comment]
Quick question, have you utilized CraftTweaker to add any new fuels to the enchanting table?

**Comment by Roadhog360** [comment]
I am able to reproduce this, and I believe I know exactly what I did wrong.
