### ISSUE TITLE
Elytra not working even with modified Smart Moving

### ISSUE THREAD

**Issue by RaidhoSketch** [Roadhog360/Et-Futurum-Requiem#265]
- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
Et_Futurum_Requiem-2.4.4+nomixin

### Describe the issue (IMPORTANT)
Yes, it's a nitpick for all we know, but ugh. It doesn't crash, the issue is that it just doesn't work. We honestly tried to find a workaround, and stumbled [here](https://github.com/makamys/SmartMoving). It says: "Et Futurum Requiem: Fully compatible with the right workarounds. // Crash on startup. Fixed by disabling skin backport (enablePlayerSkinOverlay in functions.cfg). Elytra is incompatible with PlayerAPI. Fixed by using this fork of Smart Moving + PlayerAPI." Sure. Used all the forked stuff. It doesn't crash, so success, but it still doesn't work. It evidently tries to, as we jump it switches the camera a little and we don't receive fall damage, and it sometimes even renders in the inventory screen, but the player still falls straight down.

The issue is fully reproducible with this modlist:
Et_Futurum_Requiem-2.4.4+nomixin.jar
PlayerAPI-1.7.10-1.4.jar
RenderPlayerAPI-1.7.10-1.4.jar
SmartMoving-1.7.10-15.7-maka.jar
SmartRender-1.7.10-2.1.jar
-unimixins-all-1.7.10-0.1.7.jar

**Comment by Roadhog360** [comment]
I am considering having this issue moved over there.

**Comment by makamys** [comment]
> SmartMoving-1.7.10-15.7-maka.jar

That's not the latest version, EFR compat was added after that release, I just haven't made a new release since then. I released [**15.8**](https://github.com/makamys/SmartMoving/releases/tag/15.8-maka) with the latest changes now.

> I am considering having this issue moved over there.

Feel free to move it if you can (I can't for some reason.)

**Comment by Roadhog360** [comment]
Looks like I can't, I can only transfer it to repos I own. Oh well

**Comment by makamys** [comment]
In that case @RaidhoSketch, open a new issue in the Smart Moving repo if the issue still happens with 15.8.
