### ISSUE TITLE
NoSuchMethodError - BlockDeepslateOre - (Stock) Aternos server

### ISSUE THREAD

**Issue by eggplantedd** [Roadhog360/Et-Futurum-Requiem#271]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

Et_Futurum_Requiem-2.4.5.jar

### Describe the issue (IMPORTANT)

Log: https://pastebin.com/W2r03tSn

Hopefully(?) the modlist I'm using can explain this, but the server crashes before starting on Aternos.org, no tweaks to the server files done, just installing the mods off their mod browser.

I have searched for a similar error, and found one for other items such as 'dark oak mineshafts' with the instruction to disable them (I wouldn't know how, but doesn't appear in error). There is also a mention of BlockDeepslateOre crashing a server, but that was fixed in an earlier version.

TerraFirmaCraft+ is not incompatible with this (there's a modpack that pairs the two together).

> [14:04:34] [Server thread/ERROR] [FML/]: Caught exception from etfuturum
> --
> 824 | java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149708_J()Lnet/minecraft/creativetab/CreativeTabs;
> 825 | at ganymedes01.etfuturum.blocks.ores.BlockDeepslateOre.setAttribs(BlockDeepslateOre.java:49) ~[BlockDeepslateOre.class:?]
> 826 | at ganymedes01.etfuturum.blocks.ores.BlockDeepslateOre.<init>(BlockDeepslateOre.java:35) ~[BlockDeepslateOre.class:?]
> 

### Mod list (OPTIONAL)

> UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
> --
> 810 | UCH	FML{**.**.**.**} [Forge Mod Loader] (forge.jar)
> 811 | UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge.jar)
> 812 | UCH	tfc_coremod{0.89.1} [TFC[coremod]] (minecraft.jar)
> 813 | UCH	FoamFixCore{1.0.4} [FoamFixCore] (minecraft.jar)
> 814 | UCH	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar)
> 815 | UCH	terrafirmacraftplus{0.89.1} [TerraFirmaCraft+] ([1.7.10]TerraFirmaCraftPlus-0.89.1.jar)
> 816 | UCH	aiimprovements{**.**.**.**} [AI Improvements] (AIImprovements-1.7.10-0.0.1b8.jar)
> 817 | UCH	ChunkPurge{2.1} [Chunk Purge] (ChunkPurge-1.7.10-2.1.jar)
> 818 | UCH	damagetilt{0.1.0} [Damage Tilt] (DamageTilt-1.7.10-0.1.0.jar)
> 819 | UCE	etfuturum{2.4.5} [Et Futurum Requiem] (Et_Futurum_Requiem-2.4.5.jar)
> 820 | UCH	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.4.jar)
> 821 | UCH	skinport{1.7.10-v10d} [SkinPort] (SkinPort-1.7.10-v10d.jar)

### Additional Context (OPTIONAL)

Log: https://pastebin.com/W2r03tSn

**Comment by makamys** [comment]
`func_149708_J` = `getCreativeTabToDisplayOn` (client-only)

**Comment by eggplantedd** [comment]
If that's Et Futurum, then I'll have to see which config file that setting is in.

**Comment by makamys** [comment]
Oh, I just meant that as a note to Roadhog. The deepslate ore's code calls a client-only method during its initialization. I think this would happen even with no other mods. So the only workaround for now is to disable deepslate.

**Comment by Roadhog360** [comment]
I am going to steangle whoever marked these functions as client-sided for no reason, mark my words

**Comment by GregoriusT** [comment]
Mojang uses a Compiler that automatically marks those things, resulting in some very useful functions being Clientside only for no discernible reason.

However Creative Tab info being Clientside Only is normal, and you should've known that. :P

**Comment by Roadhog360** [comment]
The field itself is not.

Anyways the person who chose to do that automatically is still guilty, strangling imminent
