### ISSUE TITLE
Inverted Daylight Sensor bug

### ISSUE THREAD

**Issue by happyburger23** [Roadhog360/Et-Futurum-Requiem#274]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
Et_Futurum_Requiem-2.4.5

### Describe the issue (IMPORTANT)
When placed during the day, Inverted Daylight Sensors (night setting) remain on, when they should deactivate at sunrise and activate at sunset.

**Comment by GregoriusT** [comment]
Just a quick random question, does your world happen to lag so hard that the daytime skybox does not sync up with the actual time? I am only saying that because I encountered that specific thing during worldgen lag. It is VERY unlikely that what I am saying is the actual cause, but you never know. ;)

**Comment by Roadhog360** [comment]
It seems like one of the redstone components attached to it needs to be updated, either by breaking the wire itself or a block next to it, or it existing during the transition from day to night when the detector's levels would change.

**Comment by GregoriusT** [comment]
Oh if it doesn't cause a Block Update then yeah that would be the Issue, Redstone always requires Block Updates in order to work properly.

**Comment by happyburger23** [comment]
![2023-05-07_11 59 51](https://user-images.githubusercontent.com/93412223/236698920-dc54c721-4980-4eb9-8396-7309b5798bd5.png)

Here's a screenshot of it in action

**Comment by happyburger23** [comment]
> Just a quick random question, does your world happen to lag so hard that the daytime skybox does not sync up with the actual time? I am only saying that because I encountered that specific thing during worldgen lag. It is VERY unlikely that what I am saying is the actual cause, but you never know. ;)

My world doesn't have any worldgen-related lag.
