### ISSUE TITLE
Large number of damage particles lagging the server

### ISSUE THREAD

**Issue by kang-png** [Roadhog360/Et-Futurum-Requiem#275]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

Et_Futurum_Requiem-2.4.2

### Describe the issue (IMPORTANT)

High damage weapons attacking entities with excessive blood will produce a large number of damage particles, resulting in high latency in the server。Very high ping

**Comment by GregoriusT** [comment]
Blood?? You mean Hearts?

**Comment by Roadhog360** [comment]
I guess you're right, perhaps I'm just being too anal about this. I've changed my mind, I will simply just make it so up to 25 hearts can display at one time.

**Comment by makamys** [comment]
Maybe every 25 hearts could be replaced with one large heart, and every 25 large hearts could be replaced by one very large heart. Well, not sure how high we need to go.
