### ISSUE TITLE
Crash on forge server with craftTweaker

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#283]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

Et_Futurum_Requiem-2.5.0-SNAPSHOT-e291a52+nomixin.jar

### Describe the issue (IMPORTANT)

If you start the server with et futurum and minetweaker the game will crash.
This doesn't happen if you run them together on the client

Also the server starts with one of them without problems, crashes only when used together

### Mod list (OPTIONAL)

	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAA	unimixins{0.1.9} [UniMixins] (-unimixins-all-1.7.10-0.1.9.jar) 
	UCHIJAA	unimixins-mixin{0.1.9} [UniMixins: Mixin (UniMix)] (-unimixins-all-1.7.10-0.1.9.jar) 
	UCHIJAA	unimixins-compat{0.1.9} [UniMixins: Compatibility] (-unimixins-all-1.7.10-0.1.9.jar) 
	UCHIJAA	mixingasm{0.2.2} [UniMixins: Mixingasm] (-unimixins-all-1.7.10-0.1.9.jar) 
	UCHIJAA	gtnhmixins{2.1.9} [UniMixins: GTNHMixins] (-unimixins-all-1.7.10-0.1.9.jar) 
	UCHIJAA	spongemixins{2.0.1} [UniMixins: SpongeMixins] (-unimixins-all-1.7.10-0.1.9.jar) 
	UCHIJAA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (-unimixins-all-1.7.10-0.1.9.jar) 
	UCHIJAA	gasstation{0.5.1} [UniMixins: GasStation] (-unimixins-all-1.7.10-0.1.9.jar) 
	UCHIJAA	mixinextras{0.1.9} [UniMixins: MixinExtras] (-unimixins-all-1.7.10-0.1.9.jar) 
	UCHIJAE	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.7.10-3.1.0-legacy.jar) 
	UCHIJAA	etfuturum{2.5.0} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.5.0-SNAPSHOT-e291a52+nomixin.jar)

**Comment by Roadhog360** [comment]
If you are sure about that you may close this issue then. A large server runs CT and EFR side-by-side so I am tempted to say that it might be MineTweaker's fault too, I once again encourage trying CraftTweaker instead (it is essentially more up to date)

**Comment by Roadhog360** [comment]
Bro I didn't click that button why does GitHub fucking do that sometimes

**Comment by kotmatross28729** [comment]
Btw, game doesn't crash when using release 2.4.6.

**Comment by xstmass** [comment]
Have same issue after update. Using latest version from git masteк branch
https://mclo.gs/hNXLyrp

Causing by this - 
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/9090102/51ff2a17-aec7-4092-98ba-72a04b4c2c1c)

**Comment by Roadhog360** [comment]
Lmk if that fixes it for ya <3
If not I can reopen

**Comment by kotmatross28729** [comment]
Server starts fine. Thanks!
