### ISSUE TITLE
Composter Automation

### ISSUE THREAD

**Issue by DragooKnight** [Roadhog360/Et-Futurum-Requiem#285]
Composter does not interact with hoppers for automated mulching.

**Comment by Roadhog360** [comment]
This is not easily fix-able in 1.7.10 because it seems hopper interaction code assumes a tile entity in which composters are not.

**Comment by DragooKnight** [comment]
Well, that's nice to know.  I suppose rewriting it into a tile entity that works like a composter would be too much... everything?

**Comment by GregoriusT** [comment]
Heh, I didnt know the SoS Label was for signaling "hey i need mixin help over here!"

But yeah Vanilla Hopper Code has a special case to check for Composters BEFORE checking for everything else, resulting in the relatively new Vanilla Lag Busting Technique of "put a Composter on the Hopper so it wont scan for TileEntities, Items or Minecarts"

**Comment by Roadhog360** [comment]
Embeddedt fixed this
