### ISSUE TITLE
[Question]: how to translate "Decoration only" for some items

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#286]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
Et_Futurum_Requiem-2.5.0-SNAPSHOT-ce20886+nomixin

### Describe the issue (IMPORTANT)

Some items have a description: "Decoration only", but there is no line in the lang file to translate this.
Also, I didn't find anything in the code that could be related to this, can you tell me where it can be viewed? (I know it's a very small thing, but I need it for a full translation)

![Снимок](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/110309314/361f6b3e-9ad8-4605-a78a-7b2eb366ca9b)

**Comment by GregoriusT** [comment]
It is in ganymedes01.etfuturum.blocks.itemblocks.ItemBlockDecorationWorkbench.java to at the very least answer the question of where it is.

**Comment by kotmatross28729** [comment]
> It is in ganymedes01.etfuturum.blocks.itemblocks.ItemBlockDecorationWorkbench.java to at the very least answer the question of where it is.

Thank you!

**Comment by Roadhog360** [comment]
Thank you Greg.
I typed my response but didn't hit send 💀
