### ISSUE TITLE
Amethyst Geodes need a better check for if the Area they spawn in contains enough Vanilla Stone Blocks or Deepslate

### ISSUE THREAD

**Issue by GregoriusT** [Roadhog360/Et-Futurum-Requiem#292]
As per https://github.com/Roadhog360/Et-Futurum-Requiem/discussions/290#discussioncomment-6522632

Amethyst Geodes need a better check for if the Area they spawn in contains enough Vanilla Stone Blocks or Deepslate.

Edit: did me linking that Reply just auto-assign you?

**Comment by Roadhog360** [comment]
Nice, thanks.
Idk if that auto-assigned you, but the template auto-assigns me so if you clicked the template but then erased all of the contents it'd assign me.

**Comment by GregoriusT** [comment]
Yeah that would do it too, considering it was a TODO or Reminder, the Template does not really handle that sorta stuff. XD

**Comment by Roadhog360** [comment]
Ok so we looked at vanilla and we double-checked that geode generation and checks is on-par with vanilla, so I may add Twilight Forest to the blacklist.
Is its dimension ID configurable? If it is not, what's the dimension ID?

**Comment by GregoriusT** [comment]
Just to be 100% sure the blacklist for GEODES ONLY right? Not for all Worldgen?

**Comment by Roadhog360** [comment]
I'll triple-check if the amethyst placement is really vanilla then, something... Seems fishy about it.

**Comment by GregoriusT** [comment]
Yeah uh this one is not strict enough for sure.

	private boolean isInvalidCorner(World world, int x, int y, int z) {
		Block block = world.getBlock(x, y, z);
		return block.isAir(world, x, y, z) || !block.isOpaqueCube() || world.canBlockSeeTheSky(x, y, z);
	}

How about checking if the Block Material is(n't) Material.rock? That way TREES do not cause this, and Dark Water would not cause this either.

**Comment by GregoriusT** [comment]
Even if you DID have the exact vanilla conditions, they would probably not work with the Forge Event Systems Worldgeneration Order, and they would not work with custom types of Ocean Water.
