### ISSUE TITLE
Cant setup Dev Environment anymore because mixins.srg is missing from the build folders.

### ISSUE THREAD

**Issue by GregoriusT** [Roadhog360/Et-Futurum-Requiem#298]
Please note I did make sure to be able to download everything, but it is still not working.

Both “gradlew build” and “gradlew setupDecompWorkspace” will result in this Error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reobf'.
> java.io.FileNotFoundException: ~/projects/minecraft/et-futurum-requiem/build/tmp/reobf/mixins.srg (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
13 actionable tasks: 5 executed, 8 up-to-date
```

**Comment by GregoriusT** [comment]
Clearing out the build directory fixed it, thanks.

**Comment by GregoriusT** [comment]
Clearing out the build directory fixed it, thanks.

**Comment by GregoriusT** [comment]
Clearing out the build directory fixed it, thanks.

**Comment by Roadhog360** [comment]
Weird, for me I can do that. What do you see? We can use this issue here as a quick test if you want.

**Comment by GregoriusT** [comment]
I can only close with a comment, but if i left the comment BEFORE closing i cant really close without leaving YET ANOTHER comment. That was my issue lol.
