### ISSUE TITLE
Random crash 2 (something with spectator mode)

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#304]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

e87ab58 used, but the cause of the crash is most likely: 15b71b20279403ec857b8bf4fff3daf35ac5c58c

### Describe the issue (IMPORTANT)

Also occurs after the creation of the world at a random moment.
Now something with the spectator mode

### Crash report
https://pastebin.com/WLrPNUVG

**Comment by Roadhog360** [comment]
I've been getting this too but unable to find the cause, I never changed the functions in the stack trace when it started happening, it's baffling me and it seems to just come out of nowhere. I've torn my code base upside down looking for the cause.

**Comment by Roadhog360** [comment]
Possibly not fixed, someone else I'm talking to on Discord who got the same crash is gonna test to be sure.
