### ISSUE TITLE
Crash (Constructing EntityFX, sand particle related?)

### ISSUE THREAD

**Issue by kotmatross28729** [Roadhog360/Et-Futurum-Requiem#308]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

10c8458bf8cfdb2f0b1390bc8807f9e61b51ba82, but POSSIBLY the cause of the crash is likely: 14cf825363baf15800a3497d3e006db2c9dd5ff0 (there were changes in this part)

### Describe the issue (IMPORTANT)

Happened to me when creating a new world (in a large modpack).

The crash is apparently rare, because I tried to reproduce it again (thanks to coretweaks) by creating 4-5 more worlds, but they were already created normally. 
(I suppose that there I spawned in a desert biome, or somewhere where there is sand, and in other worlds I spawned in a forest or somewhere else where there is no sand)

As I understand it, this is something with sand particles (ganymedes01.etfuturum.client.particle.FallingDustFX)

### Crash report

https://pastebin.com/vjx8wVbc

**Comment by kotmatross28729** [comment]
Managed to reproduce it again, also in a sand biome.
So it happens very often in places where there is a lot of sand

**Comment by Roadhog360** [comment]
Likely related to falling dust particles that come from BlockFalling. Probably related to the dust particle config in cinfigmixins
