### ISSUE TITLE
`betterPistons` sticky pistons do not properly respond to one-tick pulses

### ISSUE THREAD

**Issue by Roadhog360** [Roadhog360/Et-Futurum-Requiem#321]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

[def65b8](https://github.com/Roadhog360/Et-Futurum-Requiem/commit/def65b802f41d72388b7e05df4f4d1f2dd257718), although this issue goes as far back as the original [Back in Slime code](https://github.com/DonBruce64/BackInSlime).

First video: EFR `betterPistons`, it incorrectly pulls the block back when it should only do that on the second tick.
Second video: Back in slime pistons having the same issue, then testing with vanilla pistons to show that they're supposed to let go of the block.
[simplescreenrecorder-2023-09-05_20.20.28.webm](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/11903511/d8943fca-e187-4fbe-a8ae-52651d440477)
[simplescreenrecorder-2023-09-05_20.33.57.webm](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/11903511/772c87eb-4c5a-4f50-a25d-c11913a6b6d4)

### Describe the issue (IMPORTANT)

Giving a sticky piston a one-tick pulse when a block is in front of it should cause it to let go of the block when retracting. What actually happens is the piston seems to move slightly slower, causing it to not drop the block. This is only when giving the sticky piston a one-tick pulse. Something in the pushing code is not working as intended because if the piston does not have anything in front of it, then it moves at the normal, faster speed that theoretically would let go of the block.

### Additional Context (OPTIONAL)

Fix unknown. Tried rearranging the code some, changing update flags and attempted adding new code to fix it, but all have failed so far.

**Comment by Roadhog360** [comment]
Fixed in [aeaf360](https://github.com/Roadhog360/Et-Futurum-Requiem/commit/aeaf360744a1ec61a4021c77ed5a3788fbedc17d), from #327

**Comment by GregoriusT** [comment]
Does this mean it is enabled by default again?

**Comment by Roadhog360** [comment]
It will be, I just took a break before changing it.
