### ISSUE TITLE
Prismarine animation is not smoothed

### ISSUE THREAD

**Issue by xenoramos** [Roadhog360/Et-Futurum-Requiem#322]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
2.5.0 beta 2

### Describe the issue (IMPORTANT)
Like title says, the "Prismarine" texture in Et Futurum Requiem does not have any smoothing during transitions, but instant change between four different states. I checked "prismarine.png.mcmeta", and it is identical to other mod's prismarine (I compared to prismarine from "Village Names" mod, where transitions are smooth like in modern Minecraft). Is there any way to make Prismarine in EFR smooth too?

### Mod list (OPTIONAL)
I have tested it with only EFR and without resourcepacks

### Additional Context (OPTIONAL)
I know it's VERY small and not essential issue, but I still think it should be mentioned.
Also Botania has it's own prismarine, which is also smoothly animated, same as Village Names' one.

**Comment by GregoriusT** [comment]
@Roadhog360 so there is two or three options, either do a special renderer that does the smoothing, or look at whatever village-names did, or you just add more inbetween animation frames to the Prismarine Texture

**Comment by Roadhog360** [comment]
The animation *is* smoothed though.

**Comment by Roadhog360** [comment]
Did you actually check in game? My files are identical to the modern one. Mine has interpolation, and it seems to be working just fine on my end.

**Comment by Roadhog360** [comment]
And Greg yes they do use a special renderer, they are very clearly using a class for interpolation, that's how it's always worked, have either of you actually verified this issue in game?

**Comment by xenoramos** [comment]
Huh, that is odd. I was completely sure it has something to do somewhere deeper in the code, because "normally" interpolation always seems to fail in 1.7.10 for me, unless it is already working nicely in any mod. Even if mcmeta files are COMPLETELY same.

There's a short demonstration how it looks: https://youtu.be/1xZHRG3P2vE
First half - completely empty modpack (as I shown) with only EFR with default textures, second half - comparison to other mods I mentioned.
Maybe you could see what I messed up there :c

**Comment by Roadhog360** [comment]
It looks like I actually accidentally removed the code responsible for this. oops.

**Comment by Roadhog360** [comment]
I don't understand why I didn't see this. I looked at prismarine hundreds of times when opening up the Creative menu though!?

**Comment by xenoramos** [comment]
> I don't understand why I didn't see this. I looked at prismarine hundreds of times when opening up the Creative menu though!?

Maybe it's not as obvious-looking in the inventory? Without specifically looking at it for several seconds it's really easy to miss it. I didn't see it in inventory (in NEI in my case) for several days, just when I tried to use them in world it became more noticeable :)

And thank you for all your work (=^__^=)
