### ISSUE TITLE
Loading Exception

### ISSUE THREAD

**Issue by Ventivu** [Roadhog360/Et-Futurum-Requiem#336]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

2.5.0

### Describe the issue (IMPORTANT)

add package-info to Baubles API pls!!!!!!!!!
the API without package-info makes lots of unfixable error.

**Comment by Roadhog360** [comment]
> add package-info to Baubles API pls!!!!!!!!!
the API without package-info makes lots of unfixable error.

What are you actually asking me to do? Is this actually a bug report? What are you reporting? What is the error?

**Comment by Ventivu** [comment]
> > add package-info to Baubles API pls!!!!!!!!!
> > the API without package-info makes lots of unfixable error.
> 
> What are you actually asking me to do? Is this actually a bug report? What are you reporting? What is the error? Please answer the questions provided by the issue template...

This mod uses the API from Baubles, but does not add the corresponding description file, causing the mod using the newer version of the API to read the wrong version of the API and throw a No Such Method Error when looking for Method in API

**Comment by Roadhog360** [comment]
This mod uses the API from [Baubles **Expanded**](https://modrinth.com/mod/baubles-expanded?hl=en-US), not regular Baubles.

**Comment by Roadhog360** [comment]
FYI idk even how it crashes since with regular Baubles it just doesn't sdd compst and without it, nothing happens. Idk what you did

**Comment by Ventivu** [comment]
You can take a look at this：[BaublesRebuild](https://github.com/Ventivu/BaublesRebuild). I have learned about the API of Baubles Expanded. I think adding a description file will not invalidate the classes in baubles\api\expanded. The automatic processing patch I constructed cannot handle yours mod well. that will cause the mixin to fail. The following is the crash-report after automatic processing.
[crash-2023-09-23_00.47.28-client.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/12705688/crash-2023-09-23_00.47.28-client.txt)
I am not familiar with the use of compression-related functions in Java, which results in the size of your mod becoming inexplicably larger when processing it, and I cannot find the source of this problem.

**Comment by Roadhog360** [comment]
You don't have Baubles Expanded installed, or any version of baubles. What is a "description file" and why is it needed? You're also on 2.4.6, the latest version is 2.5.0
Also the error you're getting has nothing to even do with baubles, it looks like a weird access error. This is a different issue.

Closing due to being invalid

**Comment by Ventivu** [comment]
I send wrong!!

**Comment by Ventivu** [comment]
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/90459039/73c17456-0ea0-4166-9974-c4dd303a97d2)
[crash-2023-09-23_13.58.44-client.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/12705735/crash-2023-09-23_13.58.44-client.txt)
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/90459039/047a5af7-d2c4-4452-af38-613fedb7d7fc)
I think this is my problem, but I can&#39;t find the cause of the problem, once the automatic operation is performed (which I know is illegal) it causes the access error

**Comment by Roadhog360** [comment]
Is your fork of Baubles doing some weird ASM? It seems the crash report contains bizarre stacks of what I can assume is bytecode or something and "Bad access to protected data in getfield", which also tells me my access transformers are being messed up.

What exactly is your fork doing here?

**Comment by Ventivu** [comment]
I have not delete any class or method
idk what happend
but I fixed it yestarday
it maybe a compress error
