### ISSUE TITLE
Tuff veins are generating in random blocks

### ISSUE THREAD

**Issue by DrParadox7** [Roadhog360/Et-Futurum-Requiem#341]
### Please check any boxes that apply to you and your issue
- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
2.5.0

### Describe the issue (IMPORTANT)
I have received reports that Tuff veins are adding in random modded blocks into its veins:
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/47131096/a1112a8f-2b12-4342-9d4a-1485d600aae2)

Upon isolating the problem this occurs even with Et Futurum alone so mod incompatibility is to be ruled out:

![2023-09-29_02 56 00](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/47131096/f6c39ebb-93ea-4cc3-ab9f-bf95a1104ded)
![2023-09-29_02 51 24](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/47131096/2ca057db-96e5-4f73-90aa-b6e62c3e68be)
![2023-09-29_02 55 16](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/47131096/9f1b39d7-27f1-4d95-b3d3-f0bdfc1e87c8)
![2023-09-29_02 55 54](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/47131096/d1f0addd-c3bb-4524-93ef-3fd7f46fb804)

To replicate it, simply drink a potion of night vision and use spectator mode at the depths of the world.

### Mod list (OPTIONAL)
Here's the mod list for the paranoid bunch:

[crash-2023-09-29_03.00.50-client.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/12755020/crash-2023-09-29_03.00.50-client.txt)

**Comment by GregoriusT** [comment]
I would like to know how the heck this happens to you because i have the exact same bug in GT6 and i have no idea how the Block IDs mess up this badly!

**Comment by Roadhog360** [comment]
Oversight with the deepslate ore registry, the deepslate registry still gets them when deepslate ores are not enable. And someone designed the setBlock function to just place random shit from the block registry instead of failing the setBlock!?

**Comment by GregoriusT** [comment]
Yeah somehow setBlock sometimes actually fails to set the Block you pass as parameter, and instead just gets some random Block ID. That is how it happens in GT6, and I have no Idea how to frikkin fix that...

**Comment by Roadhog360** [comment]
As explained above, it's because EFR is placing blocks that aren't actually registered.

**Comment by GregoriusT** [comment]
Welp, guess that was not how random chunks cause that Issue then, that's just how it happens in 100% of the cases...

**Comment by Roadhog360** [comment]
I might push a fix to BugTorch to make it so any unregistered or null block placement will just fail the setBlock.

**Comment by GregoriusT** [comment]
That might be a bad idea because it would make setBlock calls even more laggy, since you need to look up an ID just to check if the ID you are gonna look up is correct.

**Comment by Roadhog360** [comment]
Probably could use a map to cache if it failed or succeeded.

**Comment by GregoriusT** [comment]
using a map to cache the result of another map does not sound like it would actually do anything, does it?
