### ISSUE TITLE
Instant Crash, No Startup

### ISSUE THREAD

**Issue by AeonCDG** [Roadhog360/Et-Futurum-Requiem#360]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
 Version 2.5.1

### Describe the issue (IMPORTANT)
 I receive exit code 1, apparently for outdated mods, instantly after startup. I don't even see minecraft open before I am back on the launcher. This, is specifically due to Futurum and a side mod for DBC, HavenCore's DBC Custom Transformations, and the supporting mod to launch it. I do not know why this occurs, as both mods are up to date.

### Mod list (OPTIONAL)

I am unable to get a crash report since it crashes before even opening the game.
Mods:
HavenCore's DBC Custom Transformations
GTNH Mixins
ET Futurum Requiem (Obviously)
JinGames Dragon Block C
JinGames JBRA Client
JinGames JRMCore

**Comment by Roadhog360** [comment]
You forgot to attach the crash report. If the game did not generate a crash report, check your logs. Are you also using the mixinless version of EFR?

**Comment by AeonCDG** [comment]
Ah, sorry I am new to this. I put the mod together through curseforge, so I am most likely using the mixenless version, or whichever is default on there.

This is the crash log https://pastebin.com/WFyK7hAD

**Comment by Roadhog360** [comment]
The default version bundles mixin, which you do not need because you already use GTNH Mixins. You can replace EFR with the mixinless version of EFR.

**Comment by AeonCDG** [comment]
ah, aight my bad, I'll check it

**Comment by AeonCDG** [comment]
Okay, yeah it works fine, sorry about that. Could have probably solved that with basic reading ability. Thank you very much

**Comment by Roadhog360** [comment]
Nw
