### ISSUE TITLE
Оранжевая цемент

### ISSUE THREAD

**Issue by iocmet** [Roadhog360/Et-Futurum-Requiem#364]
Оранжевая цемент
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/63492966/b89636fe-b293-41fb-8d7a-433680f8b7a6)

**Comment by Roadhog360** [comment]
Please actually describe the issue, and at least bother to take the time to translate your issue. All I get from translating this is "orange cement" which tells me literally nothing. What is the actual issue? Please use a translator, and use the issue template.
