### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by avescarelo** [Roadhog360/Et-Futurum-Requiem#378]
Can be the replacement of the trail by sign to the dirt be removed?

![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/26678843/96b0d6e4-9058-4a94-909a-bd38af45f09b)

**Comment by Roadhog360** [comment]
No, grass paths turn to dirt when there's not an air block above them.
The issues tab is not for questions or discussion

**Comment by GregoriusT** [comment]
Would be a good Idea to make a Config for this one to EFR, because I doubt installing GregTech 6 just for this Feature is an option. XD

Paths turning back to Dirt just because there is no Air is a really stupid "Feature" on Mojangs end...
