### ISSUE TITLE
ComposterHandler crash

### ISSUE THREAD

**Issue by happyburger23** [Roadhog360/Et-Futurum-Requiem#379]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [X] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
Et_Futurum_Requiem-2.5.1

### Describe the issue (IMPORTANT)
This issue occurs sporadically while using the mod. It has happened twice in the last half hour.

### Mod list (OPTIONAL)
[crash-2023-11-07_20.33.17-client.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/13291004/crash-2023-11-07_20.33.17-client.txt)

**Comment by makamys** [comment]
Did you attach the wrong log? This is a crash at startup (same issue as https://github.com/LegacyModdingMC/UniMixins/issues/17), and Et Futurum Requiem isn't even in the mod list.
