### ISSUE TITLE
Since the custom npc version 1.8Et Futurum Requiem AND OPEN BLOCKS the game crashes. They can only be opened with 1.7

### ISSUE THREAD

**Issue by Lasuro2099** [Roadhog360/Et-Futurum-Requiem#396]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

**Comment by Lasuro2099** [comment]
.

**Comment by GregoriusT** [comment]
Please provide the actual crash?

**Comment by GregoriusT** [comment]
Told ya the template does barely anything XD

But on a more serious note, if the Logs of the Crash are provided we MIGHT be able to do something about it.

**Comment by Roadhog360** [comment]
It asks for relevant information, which a blank page does not
