### ISSUE TITLE
Crash During initialisation - NoClassDefFoundError | S1EPacketRemoveEntityEffect

### ISSUE THREAD

**Issue by t2vee** [Roadhog360/Et-Futurum-Requiem#399]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
Et_Futurum_Requiem-2.5.1+nomixin.jar
Version: 2.5.1

### Describe the issue (IMPORTANT)

Client Loads up like normal going through initialising mods but always hits the error:
`Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/network/play/server/S1EPacketRemoveEntityEffect`.  I assumed that this was a library or dependency error but came out unsuccessful, I only get this error when using Et Futurum Requiem, removing the mod completely will let the client load like normal.  

### Mod list (OPTIONAL)
Crash Report: [https://toolbox.vee.city/opengist/t2vee/20be127fc7064637a6021f1052708da4](https://toolbox.vee.city/opengist/t2vee/20be127fc7064637a6021f1052708da4)

Forge Client Log: [https://toolbox.vee.city/opengist/t2vee/32abec16ce2e4d7a81f0f3428d04e850](https://toolbox.vee.city/opengist/t2vee/32abec16ce2e4d7a81f0f3428d04e850)

### Additional Context (OPTIONAL)
I am using `+unimixins-all-1.7.10-0.1.14.jar` with the +nomixin version but have also tried the version with and receive the same error.

**Comment by makamys** [comment]
Are you sure EFR is related to this? It seems to me that the issue is that you're using two incompatible potion extension mods, EndlessIDs and ExtendedPotions.
```
[02:10:29] [Client thread/DEBUG] [ExtendedPotionsCore/etfuturum]: Found S1EPacketRemoveEntityEffect Class: net/minecraft/network/play/server/S1EPacketRemoveEntityEffect
[02:10:29] [Client thread/DEBUG] [ExtendedPotionsCore/etfuturum]:  - Changed getId to Integer
[02:10:29] [Client thread/DEBUG] [ExtendedPotionsCore/etfuturum]:  - Patching readPacketData
[02:10:29] [Client thread/DEBUG] [ExtendedPotionsCore/etfuturum]:  - Changed reading to readInt
[02:10:29] [Client thread/DEBUG] [ExtendedPotionsCore/etfuturum]:  - Patching writePacketData
[02:10:29] [Client thread/DEBUG] [ExtendedPotionsCore/etfuturum]:  - Changed writing to writeInt
[02:10:29] [Client thread/DEBUG] [mixin/etfuturum]: Mixing common.potion.vanilla.network.S1EPacketRemoveEntityEffectMixin from mixins.endlessids.json into net.minecraft.network.play.server.S1EPacketRemoveEntityEffect
```
EFR probably just happens to be the first mod that tries to access the class that failed to get transformed, and the same thing would happen without it if you tried to use some potions in-game.

**Comment by WyattTheSkid** [comment]
I am working on a project that uses EFR as a base. When adding other mods to the project I encountered a similar error. This could be caused. by conflicting mixins. If you're using a mixin bootstrap mod, (which obviously you have to be if you're using the nomixin build) make sure that no other mods you have installed shade mixin and download coretweaks and try running again. Coretweaks will most likely show you the real error. 90% of the time these missing class or method errorsvaren't real errors. Do note I did not read the whole thing I'm at work right now. Makamys said something about potion ids, that could very well be the issue too. Hope this helps.

**Comment by makamys** [comment]
CoreTweaks's fix is unlikely to be relevant here, there's no log4j in the stacktrace.

**Comment by Roadhog360** [comment]
It's weird that I'm somehow causing this crash, because I don't touch that class or use it at all anywhere in my code.

What happens if you remove te reset fix?

**Comment by t2vee** [comment]
Ah, following @makamys solution, it appears that ExtendedPotions was causing the crashes. Removing it lets the client launch like normal.
Apologies for opening the issue for a unrelated problem, I would of never of found that so thank you anyways!
