### ISSUE TITLE
The texture of the boat is shaded when it hits the ocean water from the gt6

### ISSUE THREAD

**Issue by VadimFlex** [Roadhog360/Et-Futurum-Requiem#409]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.5.1

### Describe the Issue

The texture of the boat is shaded when it hits the ocean water from the gt6. Everything works well in river and normal water. 
![1](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/132595752/53b2a386-08e2-422f-9c8c-4620e6795600)

### Conflicting Mods

Gregtech 6

**Comment by Roadhog360** [comment]
@GregoriusT I summon thee wise for his ancient knowledge may aid in banishing this dark evil

**Comment by GregoriusT** [comment]
Where is the coordinate that is used to do the Light Level of the Boat? It might be underwater and my Ocean Blocks are supposed to darken the underwater Stuff, so the Light Level inside of them might be 0 at the height your Boats check for.

**Comment by Roadhog360** [comment]
> Where is the coordinate that is used to do the Light Level of the Boat? It might be underwater and my Ocean Blocks are supposed to darken the underwater Stuff, so the Light Level inside of them might be 0 at the height your Boats check for.

I don't know

**Comment by Roadhog360** [comment]
Looks like this isn't an EFR issue directly; notice the squid is also shaded. I have additionally confirmed this by spawning other small mobs in the water.
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/11903511/78ea77d2-6576-4fc9-8185-78aa9740d42c)

**Comment by GregoriusT** [comment]
Just for context, I have been talking with Roadhog in the background and it actually might be a GregTech-6 Issue, that is why this was closed. ;)

**Comment by VadimFlex** [comment]
> Похоже, это не проблема EFR напрямую; обратите внимание, что кальмар также заштрихован. Я дополнительно подтвердил это, создав в воде других мелких мобов. ![image](https://private-user-images.githubusercontent.com/11903511/300229678-78ea77d2-6576-4fc9-8185-78aa9740d42c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDk1MTgsIm5iZiI6MTcwNjQ0OTIxOCwicGF0aCI6Ii8xMTkwMzUxMS8zMDAyMjk2NzgtNzhlYTc3ZDItNjU3Ni00ZmM5LTgxODUtNzhhYTk3NDBkNDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDEzNDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MDhhMWI5Yjg4YzA4OWE5ZjJmOTM0MGUyZDFiZjg0Mjg3MGExZGNkZDliZTg1MTZhNjg2MTdhYTZhYzc3ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qx62nINqVQQZX0baXt7jcLURYtNzoOljI0uBwqRrgwM)

I checked it out, and yes, indeed, but this does not apply to all mobs. Apparently it depends on their height. It's amazing how I didn't notice it before.

**Comment by VadimFlex** [comment]
> Looks like this isn't an EFR issue directly; notice the squid is also shaded. I have additionally confirmed this by spawning other small mobs in the water. 

I checked it out, and yes, indeed, but this does not apply to all mobs. Apparently it depends on their height. It's amazing how I didn't notice it before.
