### ISSUE TITLE
Error generating obsidian pillars at the end

### ISSUE THREAD

**Issue by VadimFlex** [Roadhog360/Et-Futurum-Requiem#410]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.5.1

### Describe the Issue

To begin with, I note that with EFR installed (even if it is installed alone), there are often cases when obsidian pillars do not appear in the end, or they appear, but in limited quantities, which is atypical for vanilla minecraft. 
![2024-01-18_17 40 21](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/132595752/d1ef0d9f-49b5-41c4-8699-c868814a1eed)
![2024-01-18_15 29 37](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/132595752/0eb1e32f-cfca-4511-bd11-fba64e9c4de4)

When installing other mods, the opposite situation may occur - there will be too many obsidian pillars, which is atypical. Perhaps this is due to Buildcraft (I don't know how it can affect this at all), at least with the sequential installation of mods, this error appeared on this particular mod. Given the great randomness in the appearance of these pillars, this information may be false.
![2023-12-27_22 56 28](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/132595752/e6a636f0-4268-4ed2-95ba-4e3055d5671c)
![2024-01-18_18 34 06](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/132595752/a2af5900-5e32-4133-a5c1-0ae65fdd083c)

### Conflicting Mods

The Buildcraft mod may be causing the problem, but that may not be true. More tests are needed.

### Other Details

List of mods
![изображение](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/132595752/79cc092a-29a9-41f8-bf2e-2afcd5527838)

**Comment by Roadhog360** [comment]
Oh that's fucked up lmao

**Comment by VadimFlex** [comment]
> Ох это пипец, имао
> 
> Вы находитесь в среде разработчиков? EFR выполняет некоторые действия End, если мод загружен в dev, но в противном случае он вообще не затрагивает конец.

No, I am not in the dev environment. Maybe it has to do with horus?

**Comment by VadimFlex** [comment]
> Oh that's fucked up lmao
> 
> Are you in a dev environment? EFR does some End stuff if the mod is loaded in dev, but otherwise it does not touch the end at all

No, I am not in the dev environment. Maybe it has to do with horus?

**Comment by Roadhog360** [comment]
It does not, chorus fruit is a standard world generator, so it's strange it'd be causing this. Are you sure this issue is caused by Et Futurum Requiem? Have you tried producing it without EFR present?

**Comment by Roadhog360** [comment]
Issue confirmed. Oddly enough, this DOESN'T happen with the dev environment changes I mentioned earlier. I actually had to turn that OFF to get this issue to happen. Wtf

**Comment by VadimFlex** [comment]
> Have you tried producing it without EFR present?

Yes, of course I tried, there is no problem without your mod.
 
> It does indeed seem to be caused by BuildCraft+EFR too.

It's strange, because this mod does not touch the end at all

**Comment by Roadhog360** [comment]
Issue located, ocean monument generation is at fault. Not sure why BuildCraft in particular causes this error to be exposed though.
