### ISSUE TITLE
Can not place Lantern on walls

### ISSUE THREAD

**Issue by Pilzinsel64** [Roadhog360/Et-Futurum-Requiem#414]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.5.1-nomixin

### Describe the Issue

Looks like Lanterns on 1.19.2 can be placed on walls but actually this isn't possible. (I made a [discussion](https://github.com/Roadhog360/Et-Futurum-Requiem/discussions/413) before I regoniced that you wrote this should be an issue, sorry.)

![grafik](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/23138465/390a4431-6203-4080-96da-c264a13c6b49)

Thank you for your hard, I really love this mod! 🙂

**Comment by Roadhog360** [comment]
This is not in vanilla

**Comment by Roadhog360** [comment]
Wait what I never said this should be an issue what ![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/11903511/4cca81bf-c2b4-40a3-b3c9-1a188d017772)

**Comment by Pilzinsel64** [comment]
> Wait what I never said this should be an issue what

See your read first post: https://github.com/Roadhog360/Et-Futurum-Requiem/discussions/46
> Note that content already backported that is missing features or functionality is a BUG and should be reported in the issues tab.

**Comment by Roadhog360** [comment]
In any case the feature you pictures is modded, not vanilla so the statement does not apply.
Nonvanilla features will be added in a different mod I am working on
