### ISSUE TITLE
Two issues with Pink Petals

### ISSUE THREAD

**Issue by happyburger23** [Roadhog360/Et-Futurum-Requiem#416]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0-SNAPSHOT-4fb9a31

### Describe the Issue

1. Placing multiple Pink Petals' on the same block only consumes one item (4 to 3 and not 4 to 2 for example.)

Expected behavior is that 2+ get placed on the same block, and the appropriate number of items gets used.

2. When a grouping of 2+ gets broken, you get the correct amount of drops on top of the 1 that got used, which leads to easily duping them.

**Comment by Roadhog360** [comment]
This sounds like one issue, not 2

**Comment by GregoriusT** [comment]
Uh what you just fixed does NOT seem like the issue described, you fixed a creative mode thing, not the actual sync issue that leads to people believing more than one item or no item got used. You are probably either not decreasing stacksize clientside or you are not synching it from server to client after rightclicking the petal block.

**Comment by Roadhog360** [comment]
The code that consumes the item when stacking it in the block was missing. The ossue was, you place the petals into the block, break it and the petals duped because they were not consumed. Yes I fixed the issue, the description was needlessly convoluted and lists basically the same issue twice.
