### ISSUE TITLE
TileEntityBannerRenderer no smooth flag waving animation when worldTime is large

### ISSUE THREAD

**Issue by Natsukiw** [Roadhog360/Et-Futurum-Requiem#419]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.6.0

### Describe the Issue

It usually appears in the server and the value of worldtime is too large.
I tried a repair and it worked.

At methd renderTileEntityAt()
long worldTime = (banner.getWorldObj() != null ? banner.getWorldObj().getTotalWorldTime() : 0) % 1000;

**Comment by Roadhog360** [comment]
`long worldTime = (banner.getWorldObj() != null ? banner.getWorldObj().getTotalWorldTime() : 0) % 1000;` Are you sure this wouldn't cause a jump in the banner's animation every 1000 ticks?

**Comment by Roadhog360** [comment]
Issue could not be reproduced after setting the in-game time to 2 billion ticks. I also got a similar report for beacons, and once again was completely unable to reproduce the issue.

**Comment by makamys** [comment]
Day time (`DayTime` in `level.dat`, which is what `/time set` sets) is *not* the same thing as the world time (`Time`, which increments by 1 each tick). If I change time to a high value, I can reproduce the issue. At around 3280000 the flag abruptly stops waving.

**Comment by Roadhog360** [comment]
Hm... I suspect mod 1000 would cause abrupt jumps in the animation, I feel as if we need to find a more specific value to wrap around the value.

**Comment by Roadhog360** [comment]
What if we used Math.cos? What exactly is the difference anyways?

**Comment by makamys** [comment]
I should also note that the issue also happens in a freshly created world if you go farther than X=467000, since the banner's coordinates are piped into the equation.

**Comment by makamys** [comment]
> What if we used Math.cos? What exactly is the difference anyways?

We should just avoid using large float values entirely, with Math.cos the corruption just becomes different. (The banner animation becomes choppy rather than stopping entirely.)

**Comment by Roadhog360** [comment]
Hm, I think for the coords I could probably mod it to not go past thst value, just loop back around. What should I mod the world time by?

**Comment by Roadhog360** [comment]
Hm, I think for the coords I could probably mod it to not go past thst value, just loop back around. What should I mod the world time by? Maybe 3280000 or something so the skip in animation is rare?

**Comment by makamys** [comment]
I think I figured it out, I replaced it with equivalent math that avoids large values.
https://github.com/Roadhog360/Et-Futurum-Requiem/commit/7e8d829ca1583ee151bfbaeaf163c85e2bf628bb
Also derp, I tagged the wrong issue in the commit

**Comment by Roadhog360** [comment]
Does this not skip the animations at all?

**Comment by makamys** [comment]
Nope, it's smooth. The idea is that `cos` is periodic with a period of `2*PI`, so `x*2*PI` is the same thing as `(x%1)*2*PI`. You can see that I split it apart like that in the code: `MathHelper.cos(f3 * 0.01F * 2F * (float) Math.PI)`. And since `f3` is modulo'd by 100, that means `f3 * 0.01F` is modulo'd by 1. So that checks out.

And adding in the extra modulos in `animationProgress100`'s equation doesn't change anything either.
`(x+y)%100==((x%100+y%100)%100)`, and `(x*y)%100==((x%100)*y)%100`. Proving this is left as an exercise to the reader :tm:
