### ISSUE TITLE
Sponges and BOP

### ISSUE THREAD

**Issue by NetherDog** [Roadhog360/Et-Futurum-Requiem#425]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0-SNAPSHOT-7e8d829

### Describe the Issue

The Coral Reef biome (BOP) generates sponges on the ocean floor. Before installing EFR, everything is fine, because the sponges do not have functionality.
![1](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/159978364/cd0920bc-4f5d-4807-bf6b-10ef025fb6a5)
![2](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/159978364/a10cb654-a269-43f9-b1d8-3acaf725a00a)

**Comment by Roadhog360** [comment]
Hm... Maybe then I will make it so naturally generated sponged will be wet sponged instead.

**Comment by makamys** [comment]
IIRC VillageNames' approach was to keep the vanilla sponge block non-functional (and rename it to "inert sponge"), and make its own functional sponge blocks exclusive to ocean monuments. If you want to preserve vanilla balance, something like that would make more sense.

**Comment by Roadhog360** [comment]
I can actually check if a chunk is conpletely generated in, so I will make the replacer simply place wet sponges if that is the case.

**Comment by Roadhog360** [comment]
Looking to fix this, there is no "Coral Reef" biome in BOP worlds, nature's compass shows no such biome. Please explain the exact in-game name of this biome.

**Comment by makamys** [comment]
I don't know about Nature's Compass, but I know for a fact there's a BoP biome called exactly "Coral Reef".

**Comment by Roadhog360** [comment]
In what version? NC scans the entire biome registry, it's simply not there. Every other biome is though.

**Comment by makamys** [comment]
1.7.10. I just checked in a fresh instance with these mods:
- `BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar`
- `naturescompass-1.4.0-GTNH.jar` or `NaturesCompass-1.7.10-1.3.1.jar`

And it's there:
![](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/13667520/567f9d8e-c970-4bd5-8203-eb710e9f9d32)
(Also my testing world spawned me right next to one, lol. The seed was 2290873208246545165, and there are some sponges at x=340, z=1200)

I can only guess that you've got some faulty configs that are causing the biome id to not be set, or to be overwritten to be something else.

**Comment by Roadhog360** [comment]
Looks like coral reefs were getting overwritten by "WitchwoodForest" from Ars Magica 2, as that is the biome present at the coordinates you specified.

**Comment by makamys** [comment]
Average numeric ID moment

**Comment by Roadhog360** [comment]
So my usual solution of checking `sendUpdates` on a chunk doesn't appear to be working. I'm trying to think of how I can solve this. Thing is I've been using the vanilla MC sponge for an ItemBlock so it effectively is what places the Et Futurum sponge, then the EFR sponge drops the vanilla one as an item (for recipe support)

**Comment by Roadhog360** [comment]
Ok, for now I'll use reflection to change the BOP world generator to use Et Futurum wet sponge. When 2.7.0 rolls around I'll change it to a mixin. I might also make a world generator that replaces naturally generated sponge with wet sponge on world generation in the future, in a similar fashion to how coarse dirt or deepslate works.

**Comment by Roadhog360** [comment]
![2024-03-20_01 04 44](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/11903511/34855ef9-1bf5-4259-b266-9991540df1fd)
BOP now places EFR wet sponge when enabled instead. This behavior will be tweaked in the future.
