### ISSUE TITLE
Vanilla "Smooth" Double Slabs have inconsistent drops

### ISSUE THREAD

**Issue by connor135246** [Roadhog360/Et-Futurum-Requiem#428]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.5.1

### Describe the Issue

Breaking `minecraft:double_stone_slab:8` drops `etfuturum:smooth_stone`.
However, breaking `minecraft:double_stone_slab:9` does not drop `etfuturum:smooth_sandstone` and breaking `minecraft:double_stone_slab:15` does not drop `etfuturum:smooth_quartz`. These should probably be consistent.

Relevant code:
https://github.com/Roadhog360/Et-Futurum-Requiem/blob/52f43ffe1de241d55163c55aaa03b1eb6135ec91/src/main/java/ganymedes01/etfuturum/core/handlers/ServerEventHandler.java#L1735-L1741

**Comment by Roadhog360** [comment]
Ooh, nice catch. I forgot about those variants.
