### ISSUE TITLE
PHC + EtFR = double mutton 

### ISSUE THREAD

**Issue by avescarelo** [Roadhog360/Et-Futurum-Requiem#433]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.5.1

### Describe the Issue

Hi!
I have the mods Pam's Harvestcraft and Et Futurum, both mods add a drop of mutton and if you kill sheep, you will get a double drop. 

Each sheep has 1-2 pieces of its own version of mutton. Is there anything we can do about it?

### Conflicting Mods

no

**Comment by Roadhog360** [comment]
You can turn off Et Futurum mutton in the config to avoid conflicts like this

**Comment by GregoriusT** [comment]
I think pams mutton can do the same with config, i would recommend getting rid of pams version honestly.

general {
    B:enablebeehiveGeneration=false
    B:enablesaltGeneration=false
    B:enablesaltfromwaterbucketrecipe=false
    B:sheepdropMutton=false
    B:squiddropCalamari=true
}
