### ISSUE TITLE
EFR Mixin Crash with floor & ceiling buttons

### ISSUE THREAD

**Issue by Aivech** [Roadhog360/Et-Futurum-Requiem#434]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.5.1.jar

### Describe the Issue

Access Transformer conflict applying mixin to buttons, similar to #390

### Crash Report

https://paste.ee/p/EsZ5h

**Comment by Aivech** [comment]
I'll just disable the mixin in the config until the fix is released, then?

**Comment by Roadhog360** [comment]
Such is a valid approach yes. You can also apply the mixin json from 2.6.0 builds to your 2.5.1 jar and it should fix it.
