### ISSUE TITLE
Netherite Boots armor value is incorrect

### ISSUE THREAD

**Issue by Omgise** [Roadhog360/Et-Futurum-Requiem#439]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0-SNAPSHOT-847fb6c+nomixin

### Describe the Issue

It should have the same armor value as diamond boots.
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/106000018/24d934fe-a6a0-4f35-99ef-5a9f6556d20c)
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/106000018/42d02f3f-e4c9-48b6-8cdb-56d7637916b6)

**Comment by Roadhog360** [comment]
Oops

**Comment by Roadhog360** [comment]
Looks like the default value is 3 as intended; check your `configblocksitems.cfg` as you have edited the values.

**Comment by Omgise** [comment]
Thank you, but the strange thing is that my configuration value here is -3, and I haven't changed the configuration here before
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/106000018/75686402-ec5a-4f38-98f2-231b6be6ff7f)

**Comment by Roadhog360** [comment]
The default value is 3 so somehow it must have gotten changed. As the minimum is 1, the game adjusted your -3 to 1.

**Comment by makamys** [comment]
Lol yeah, it used to be set to -3 by default in one of the 2.4.4 dev builds. This was fixed the next day (in https://github.com/Roadhog360/Et-Futurum-Requiem/commit/28891d0524caeabdf5b9da7ba3619fe95a5e7098).
