### ISSUE TITLE
Possible incompatibility with B3M Mod

### ISSUE THREAD

**Issue by Martin681** [Roadhog360/Et-Futurum-Requiem#445]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.5.1

### Describe the Issue

Hello there, I have a possible incompatibility issue while using this mod with B3M mod, makes the B3M cmds kinda unusable + the time cycle is kinda glitchy and the sun/moon doesnt move smoothly on the sky (as intended to be) + the moon is bloodyred. Any ideas. I searched thru the B3M and et futurm configs for some options, but no clue. The 1.7.10 folder in the mods folder is empty!
![bug](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/59067005/0346909b-c5bb-40d6-ae2b-0588406de707)
![dd](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/59067005/006a3030-844b-4499-b6cf-483840f07f2e)

I put the latest log at the bottom if that helps. Also i forgot to say that im using the latest forge version 1.7.10 - 10.13.4.1614 + liteloader

### Other Details

[latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/14779763/latest.log)

**Comment by Roadhog360** [comment]
There doesn't seem to be anything in EFR which would cause this. Have you confirmed this issue does not happen with EFR installed?

**Comment by Martin681** [comment]
yes I have the et futurm mod (not the requem one) with tons of other mods and no issues! Only if i put the Et Futurm Requem it happens. Also I tired the B3M mod completely alone, everything is in order!

**Comment by makamys** [comment]
Try adding UniMixins. B3M has a non-idempotent transformer which isn't going to work well with mixins; the Mixingasm module fixes that.

**Comment by Roadhog360** [comment]
Don't forget to change EFR to the "nomixin" version before doing that. As a side note I didn't know conflicts like this could happen... I thought ASM conflicts always resulted in crashing.

**Comment by makamys** [comment]
> Don't forget to change EFR to the "nomixin" version before doing that.

Technically not necessary since the `+` prefix in the UniMixins jar name ensures it runs first, but it's still good practice, sure.

> I thought ASM conflicts always resulted in crashing.

In the Mixin-ASM case it just means the patch doesn't get applied, that doesn't necessarily mean a crash. Here's another example with some more explanation: https://github.com/makamys/MAtmos/issues/6

**Comment by Martin681** [comment]
> Try adding UniMixins. B3M has a non-idempotent transformer which isn't going to work well with mixins; the Mixingasm module fixes that.

OMG it worked perfectly! Thank you man.
