### ISSUE TITLE
Crash on picking up Deepslate Infused Ores

### ISSUE THREAD

**Issue by RaidhoSketch** [Roadhog360/Et-Futurum-Requiem#446]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0_beta-1+nomixin

### Describe the Issue

The deepslate infused ores do not only not have a complete texture and swear about it in the logs, but attempting to grab those into the inventory either crashes or, when grabbing those from NEI, permanently bricks the world.

Also, a [Suggestion]. Currently, only one config disables all raw-ore content - including the compat blocks. We ask for a separate config for enabling just _some_ raw ores, as well as deepslate ones - this is mainly applicable when someone already has a custom ore generator (like, say, with CustomOreGen), or just wants to play without them.

### Other Details

Here's the [crash itself](https://gist.github.com/RaidhoSketch/98977c6986ff76d31c842e6530e5f80c).
The [fml log](https://gist.github.com/RaidhoSketch/3a84fab08b13946a8e41747a8a8d09a7) (just in case, look for "tesselating").

**Comment by Roadhog360** [comment]
Fixed in [43d693a](https://github.com/Roadhog360/Et-Futurum-Requiem/commit/43d693aa2c6fe0877152780799a0cfc55262d16a).

Please post suggestions in the discussion tab. There are already options to turn off only compat blocks in `modcompat.cfg`
