### ISSUE TITLE
item entity slowfall

### ISSUE THREAD

**Issue by OlorinIV** [Roadhog360/Et-Futurum-Requiem#448]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.6.0-beta1-nomixin

### Describe the Issue

new issue from 2.6.0-beta1: dropped items fall slowly in air

**Comment by Roadhog360** [comment]
Conflict with ArchaicFix, disable ArchaicFix entity item optimizations, or EFR's fireproof items in `mixins.cfg`. (this will make Netherite flammable)

**Comment by huihiuhuai** [comment]
> Conflict with ArchaicFix, disable ArchaicFix entity item optimizations, or EFR's fireproof items in `mixins.cfg`. (this will make Netherite flammable)

can't find the exact ArchaicFix entity item optimizations, is the name changed?

**Comment by huihiuhuai** [comment]
B:itemLagReduction=false

**Comment by Roadhog360** [comment]
ArchaicFix has now released a bug where their option no longer has this conflict.

**Comment by JL2210** [comment]
Pin?

**Comment by Roadhog360** [comment]
> Pin?

This request seems reasonable enough. I'll leave it pinned for a few more weeks.

**Comment by Roadhog360** [comment]
Ope max 3 pins, nvm
