### ISSUE TITLE
Recipes use an OreDict Item as Output directly, without copying it before

### ISSUE THREAD

**Issue by bioastroiner** [Roadhog360/Et-Futurum-Requiem#455]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0_beta-2

### Describe the Issue

as discussed in gregcord etfuturum's new ores furnace recipemaps output oredictionary isntead of items which got detected by gt6!

![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/68257484/f1f9536a-5aa6-4631-9818-c5e021f42c2e)
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/68257484/1ba81645-4c83-4680-8f1b-13e0365571d8)
![image](https://cdn.discordapp.com/attachments/1218995080006864946/1230270108958724117/image.png?ex=6632b553&is=66204053&hm=fb9df7fa1f5c24aab3a351d131243595b025e76a90b4428dc445897f7a52b850&)

**Comment by RaidhoSketch** [comment]
Ahh, this _might_ be why RotaryCraft's grinder registers those as empty.
