### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by avescarelo** [Roadhog360/Et-Futurum-Requiem#464]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0_beta-2

### Describe the Issue

In the ThaumicHorizonts addon, the process of creating a pocket dimension. (to excite the node, put 6 stabilizers and 4 additional devices on the node). Then I threw a singular pearl at him, the creation process began and it crashed

### Crash Report

https://gist.github.com/avescarelo/0cfe4433c7fefe65484ebb583652c5a2

### Other Details

https://gist.github.com/avescarelo/555144637facb26c60a5e78220cd9c9b

**Comment by avescarelo** [comment]
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/26678843/86297d2c-e8e8-469b-b0cb-50c7b8064b63)
Fixed crash by this

**Comment by Roadhog360** [comment]
Update to rc-1

**Comment by Roadhog360** [comment]
Have you tried updating to at least rc-1 yet? (rc-2 is preferred)

**Comment by Roadhog360** [comment]
As there has been no response regarding the result of updating, and a fix to an almost identical crash under some different circumstances has been confirmed as of rc-1, I will assume this is resolved.
