### ISSUE TITLE
Various deepslate ores have no ore dictionary / wrong ore dictionary

### ISSUE THREAD

**Issue by msparkles** [Roadhog360/Et-Futurum-Requiem#471]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.6.0-nomixin

### Describe the Issue

List of ores that don't have oredict:
- coal
- lapis
- diamond
- emerald
- charged certus (should be oreChargedCertusQuartz)

List of ores that have wrong one(s):
- certus (it should be oreCertusQuartz)

(this list is not exhaustive, these are merely the ones that we have in NEI, no idea about other compat ores.)

**Comment by Roadhog360** [comment]
Confirmed
Not sure when charged certus got a tag or when certus quartz `oreCertus` was changed to `oreCertus` though. Maybe it was updated in a fork that I'm using? It was definitely NOT like this before.

**Comment by Roadhog360** [comment]
I should just copy from the base blocks, typing it all out manually causes exactly issues like this

**Comment by msparkles** [comment]
RE: certus quartz

It might be because we're using the GTNH ae2 fork, but we doubt that, that would break a lot of recipes if they did that.

**Comment by Roadhog360** [comment]
I'll just make it copy it from the block

**Comment by Roadhog360** [comment]
Please try [aa3f7a1](https://github.com/Roadhog360/Et-Futurum-Requiem/commit/aa3f7a1895aa43db8f7250ff2f2dce0b9575bae4) when it is finished building and let me know what you think. Works for me but I wanna be sure it does for you too.

**Comment by msparkles** [comment]
@Roadhog360 redstone still has no oredict

**Comment by Roadhog360** [comment]
There ya go
