### ISSUE TITLE
Slowly falling items bug

### ISSUE THREAD

**Issue by Margatroidu** [Roadhog360/Et-Futurum-Requiem#475]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.6.0

### Describe the Issue

I play on FTB Infinity Evolved. In the latest version of mod, when I throw items out they freeze in the air and start falling slowly.

https://github.com/Roadhog360/Et-Futurum-Requiem/assets/165489993/41350402-a0f3-4bfa-bd50-de54d58c6a21

**Comment by Roadhog360** [comment]
Duplucate of #448
