### ISSUE TITLE
Shulkers can be stacked inside of shulkers

### ISSUE THREAD

**Issue by broscolotos** [Roadhog360/Et-Futurum-Requiem#487]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0

### Describe the Issue

In the vanilla game you can't place shulkers inside of another shulker however in ET-Futurum you can. Reproduction steps shouldn't be needed but don't want to get flagged for not following template.

1. place shulker
2. place 2nd shulker inside inventory of first shulker

**Comment by Roadhog360** [comment]
Do other items that are on the item blacklist also go into shulker inventories?

**Comment by broscolotos** [comment]
No, items on the blacklist in functions.cfg don't get placed. It appears that the only thing "wrong" is that the shulkers aren't on their own blacklist by default. Easy enough for individuals to fix but it should probably be added to that list.

**Comment by Roadhog360** [comment]
Shulkersare always supposed to be on the blacklist regardless of what the list's contents are.
