### ISSUE TITLE
EFR Trapdoors have a different Break sound than Vanilla Trapdoors

### ISSUE THREAD

**Issue by Omgise** [Roadhog360/Et-Futurum-Requiem#488]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

etfuturum-2.6.0-master.25+b8b1a5c471

### Describe the Issue

https://github.com/Roadhog360/Et-Futurum-Requiem/assets/106000018/ac294646-bfcd-4c1a-9e5e-0f4f7d372c86

The sound of EFR Trapdoors breaking is the sound of stones

**Comment by DarianLStephens** [comment]
Huh, it's stone instead of wood.
I don't think it was always like that, when could it have changed?

**Comment by Roadhog360** [comment]
When I fuck up the code
