### ISSUE TITLE
The anvil will show different names in Waila depending on where it is placed

### ISSUE THREAD

**Issue by Omgise** [Roadhog360/Et-Futurum-Requiem#497]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

etfuturum-2.6.0-master.35+d123e61216

### Describe the Issue

https://github.com/user-attachments/assets/abf98387-4717-4017-8cf3-64c1bff83574

**Comment by Roadhog360** [comment]
The extra Et Futurum Requiem anvil, beacon, brewing stand, etc will be phased out in a future update. This issue is also generally a low priority since it would take more effort that it's worth to fix, and it's for content that is soon to be deprecated.

**Comment by Roadhog360** [comment]
Oh P.S. vanilla WAILA has issues similar to this with vanilla blocks anyways lol. Vanilla anvil doesn't have it but non-oak logs do for example
