### ISSUE TITLE
Observer can't detect changes in the note block

### ISSUE THREAD

**Issue by ABKQPO** [Roadhog360/Et-Futurum-Requiem#499]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

etfuturum-2.6.0-master.40+47e7965a12.jar

### Describe the Issue

Yes, that's right. I'm not sure if it's due to the working principle of the note block

**Comment by Roadhog360** [comment]
This is not fixable. Note blocks do not fire updates in 1.7.10.
