### ISSUE TITLE
Adding TConstruct smeltery compatibility to raw ores via modtweaker 2 crashes the game

### ISSUE THREAD

**Issue by ScarySpookster** [Roadhog360/Et-Futurum-Requiem#521]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0

### Describe the Issue

Since raw ores do not normally have compatibility with the TConstruct smeltery I've decided to add compatibilty via Minetweaker and Modtweaker scripts, however adding smelting recipes to raw ores consistently crashes the game. 

The crash does not seem to happen if the new deepslate ores are scripted to interact with the TConstruct smeltery.

### Conflicting Mods

Modtweaker
Minetweaker

### Crash Report

https://gist.github.com/ScarySpookster/464db4d55d226d0a0777797ee520f170

**Comment by Roadhog360** [comment]
EFR already has raw ore compat with TConstruct built-in, but it is currently broken; this is what is crashing your game.

This has already been fixed and is set to release in 2.6.1, try the latest CI builds.
