### ISSUE TITLE
crash when open gui with items on backhand

### ISSUE THREAD

**Issue by iamsoNewBee** [Roadhog360/Et-Futurum-Requiem#524]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

backhand-1.5.12

Et_Futurum_Requiem-2.6.0

### Describe the Issue

I opened the blast furnace with torches on my backhand. If done twice, it will crasheed.

### Conflicting Mods

backhand

### Crash Report

https://gist.github.com/iamsoNewBee/4937c0cc9bae80b83a384847faee3dad

**Comment by Roadhog360** [comment]
"Latest" is not a valid response tothe version. Please put the actual version like the template tells you to do.

**Comment by iamsoNewBee** [comment]
Edited.

**Comment by Roadhog360** [comment]
Only one of the issues I mentioned has been fixed; the crash report is still a manual download instead of on a paste website

**Comment by iamsoNewBee** [comment]
Like this? It may be a little long

**Comment by Roadhog360** [comment]
No, like using pastebin or gist, rather than a huge wall of text

**Comment by iamsoNewBee** [comment]
I am not so familiar with this. So please doneload XD.

**Comment by Roadhog360** [comment]
I will do it for you this one time to demonstrate what I mean.

**Comment by Roadhog360** [comment]
You visit https://gist.github.com or https://pastebin.com/ and paste your text....

**Comment by iamsoNewBee** [comment]
Edited.

**Comment by Roadhog360** [comment]
Unrelated to Et Futurum Requiem, fixed on Backhand's end
