### ISSUE TITLE
Bed has two recipes

### ISSUE THREAD

**Issue by Omgise** [Roadhog360/Et-Futurum-Requiem#525]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

etfuturum-2.6.0-master.60+3c6fd4c943

### Describe the Issue

I noticed that when making other colored EFR mod beds, they also had two recipes.
The only two mods I used were EFR and Nomorerecipflict
![image](https://github.com/user-attachments/assets/23504c63-6f6a-4e17-8131-1252bc3feff4)
![image](https://github.com/user-attachments/assets/9ff89d64-e439-4780-873c-6d19b07ac5cf)

**Comment by Roadhog360** [comment]
Each bed has a specific recipe for its color as well as a wildcard recipe that falls back to the red bed. This is intended behavior.

**Comment by Roadhog360** [comment]
Since you used 3 white wool, the white bed should be what comes first, if it isn't then I'll reopen this because the white bed should have came first.

**Comment by Omgise** [comment]
Yes, the white bed is top priority.
