### ISSUE TITLE
Game Assets are downloaded each time the game is launched

### ISSUE THREAD

**Issue by Errormacromwn** [Roadhog360/Et-Futurum-Requiem#526]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0

### Describe the Issue

Every time I launch the game, Assets Director downloads the same files.

### Other Details

the only thing I could add is that I'm using SKlauncher as launcher, I don't know if that has anything to do with it.

**Comment by Roadhog360** [comment]
Launcher is probably changing the asset location in a way mods can't detect, or deleting things in that folder. It is a cracked launcher and thus is not supported, TLauncher seems to also break our asset downloader. Consider switching to MultiMC, PolyMC or Prism

**Comment by Roadhog360** [comment]
Future inquiries should be handled at [MCLib](https://github.com/makamys/MCLib/issues)'s repository, as the asset downloader is powered by [MCLib](https://github.com/makamys/MCLib/issues).

**Comment by Errormacromwn** [comment]
> Launcher is probably changing the asset location in a way mods can't detect, or deleting things in that folder. It is a cracked launcher and thus is not supported, TLauncher seems to also break our asset downloader. Consider switching to MultiMC, PolyMC or Prism

Yes, I noticed, it directly deletes the folder. it seems that the only way to mitigate this is to change the launcher, or paste the files after it deletes them, lol

**Comment by Roadhog360** [comment]
Yeah then there's nothing we can do lol, launchers shouldn't be flagrantly deleting random crap, please use a better one

**Comment by Roadhog360** [comment]
You could also revoke write access to the folder and make it so you can't delete it without admin perms so the launcher can't remove the folder, but I still strongly recommend a different launcher, I've read online about shady things and high CPU usage with this launcher.
