### ISSUE TITLE
when EFR bunny is affected by starminer gravity it crashes game wow

### ISSUE THREAD

**Issue by brandyyn** [Roadhog360/Et-Futurum-Requiem#529]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

etfuturum-2.6.0-master.37+6e423f8d6c

### Describe the Issue

when EFR bunny is affected by starminer gravity it crashes game wow

### Conflicting Mods

Starminer1710-0.9.9

### Crash Report

https://mclo.gs/ZX3h9d1

### Other Details

[crash-2024-10-12_20.41.15-server.txt](https://github.com/user-attachments/files/17351274/crash-2024-10-12_20.41.15-server.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/17351276/fml-client-latest.log)

**Comment by Roadhog360** [comment]
Let me know if that worked

**Comment by Roadhog360** [comment]
No response so assuming it's fixed since this should address the crash involved. Honestly don't feel like testing. If it still happens somehow comment and I'll reopen.

**Comment by brandyyn** [comment]
![image](https://github.com/user-attachments/assets/57ae07c5-a603-42a2-8b95-4d4ce348c744)
