### ISSUE TITLE
Unable to launch with 2.6.1

### ISSUE THREAD

**Issue by LunatiK-ExpiX** [Roadhog360/Et-Futurum-Requiem#548]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.6.1

### Describe the Issue

When attempting to launch 2.6.1, it will crash due to java.lang.NoSuchFieldError

### Conflicting Mods

Possibly Unimixins, since it is directly related to this error

### Other Details

[log.txt](https://github.com/user-attachments/files/17611598/log.txt)

**Comment by LunatiK-ExpiX** [comment]
Found the issue

**Comment by Roadhog360** [comment]
Hey there! Can you please describe what the issue was?
