### ISSUE TITLE
Cherry chest boat missing lang

### ISSUE THREAD

**Issue by AlexGuignard** [Roadhog360/Et-Futurum-Requiem#549]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.6.0

### Describe the Issue

Cherry chest boat missing lang
![image](https://github.com/user-attachments/assets/c4a82066-0f09-4a43-973c-46ff11ff194e)

**Comment by Roadhog360** [comment]
This was fixed in https://github.com/Roadhog360/Et-Futurum-Requiem/commit/362439b6e1e1d415fdd0053559b7f562642523e9 which released after 2.6.1. Please use the latest version before opening bug reports.
