### ISSUE TITLE
[Quesetion]Can I add custom raw ore textures for other mod?

### ISSUE THREAD

**Issue by iamsoNewBee** [Roadhog360/Et-Futurum-Requiem#562]
### Mod Version

etfuturum-2.6.2

### Describe the Issue

As the title. Mainly for Beryllium (HBM). If I can, Im not very sure what supposed to do :(

**Comment by Roadhog360** [comment]
Mod support suggestions go in discussions

**Comment by Roadhog360** [comment]
The bee nest uses special dropping behavior because it needs to preserve data from its tile entity
