### ISSUE TITLE
Bluepower Stone Tiles not available due to Furnace Recipe Conflict

### ISSUE THREAD

**Issue by GregoriusT** [Roadhog360/Et-Futurum-Requiem#65]
So because there is a Recipe to turn Vanilla Smooth Stone into even Smoother Stone in the Furnace, Bluepower Stone Tiles for its Circuits, which are also using Stone in a Furnace, cannot be crafted anymore.

I'm opening this Issue, because I'm not in charge of Design Decisions (which is a good thing because I dont stay perfectly up to date with the details of latest MC). I could easily fix it myself somehow if needed. ;)

Original Report I received: https://cdn.discordapp.com/attachments/320192373437104130/867684022092431381/unknown.png

**Comment by Roadhog360** [comment]
Do you have any ideas for what the alternative recipe could be?

**Comment by GregoriusT** [comment]
Well you could make it so you can smelt a Stone Slab into a Stone Tile. Not like halving the cost of that thing would make any dent in the Balance. ;)

Or you smelt the Smoother Stone into the Stone Tile, which would be an okayish Option.

**Comment by Roadhog360** [comment]
Smooth stone is already the smelting recipe, so I would consider the first one... Except by default the stone slab is crafted using the smooth stone block.

**Comment by DarianLStephens** [comment]
I feel like it should be changed for Redpower, specifically cutting the smooth stone slabs or smelting them yet again to yield the tiles.

**Comment by makamys** [comment]
For reference, in the latest version of Bluepower, the recipe is [2 ![image](https://user-images.githubusercontent.com/13667520/140870083-05c39076-cc39-4c04-880b-2c674f5a9489.png) Smooth Stone next to each other → 4 Stone Tile](https://github.com/Qmunity/BluePower/blob/92ab018d9fd14261a405e0d8138526da3ea38cf9/src/main/resources/data/bluepower/recipes/stone_tile.json).

**Comment by GregoriusT** [comment]
I said SMOOTHER Stone not Smooth Stone, referring to just having to smelt it twice in a row to get the Tiles.

Having two Smoother Stone Blocks to make 4 Tiles as suggested above seems nice too.

Do we have a Stone Cutter already? Would it make sense to put the Recipe for Stone Tile in there? Also make sure NEI knows about it so people dont need to look it up ofcourse. ^^

Note: GT6 has a Recipe that results in 9 of those Stone Tiles per Stone Block, so balance is not really important in this particular case.

**Comment by DarianLStephens** [comment]
The new crafting blocks would definitely be a nice next thing to do besides the End.
Stonecutter, Cartography Table... I guess those are actually it, huh?

FutureMC recently backported the new villager trade GUI, maybe that could be looked in to for Et Futurum?

**Comment by GregoriusT** [comment]
It's lovely how everybody called regular "Stone" Smoothstone, and then Mojang adds the name Smoothstone to that Double Slab Block with Metadata 8, and everyone gets confused... That is why I said "Smoother Stone". XD

As for NEI, it has a lot of things you just "have to know in advance", like how it just loads the Plugins based on a File inside the Jar with a specific Name. Haven't looked at my own NEI Code in a long time, hope I can maybe make something for Et Futurum...

**Comment by GregoriusT** [comment]
I made an NEI Plugin for the Smoker and Blast Furnace, though the usefulness of that is yet to be determined, considering it is literally a copy of the Furnace Handler. ;)

**Comment by embeddedt** [comment]
For now I've just implemented the new BluePower recipe if it's detected.
