### ISSUE TITLE
Crashing with Twilight Forest

### ISSUE THREAD

**Issue by gmnovakrc** [Roadhog360/Et-Futurum-Requiem#75]
Game crashes after arriving in dimension right after some chunks start to load in.
Not sure which mod is causing it though, seems to be a specific block though.
Will be posting this in Twilight Forest issues as well just in case.

Et Futurum Requiem 1.7.10-2.2.1
Twilight Forest 1.7.10-2.3.8

[crash-2021-09-26_18.15.11-server.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/7232382/crash-2021-09-26_18.15.11-server.txt)

**Comment by jss2a98aj** [comment]
This has been fixed for a bit, but an update with it has not been pushed yet.
