### ISSUE TITLE
Skin rendering issues on some mobs

### ISSUE THREAD

**Issue by Khikki** [Roadhog360/Et-Futurum-Requiem#8]
Hah, hi, I'm very interested in your Requiem, well, the problem is still the same: 'Et-Futurum', such as 'Twilight Forest', 'Headcrumbs', and 'Botania'.

Twilight Forest - Giant Miner.
![image](https://user-images.githubusercontent.com/35336209/106980047-2d590300-6768-11eb-9991-b50d6fd7a6e8.png)

Headcrumbs - Heads.
![image](https://user-images.githubusercontent.com/35336209/106980065-35b13e00-6768-11eb-86ea-c2fa885b58f6.png)

Botania - Gaia Guardian's and Head.
![image](https://user-images.githubusercontent.com/35336209/106980101-42359680-6768-11eb-911f-09e630254e89.png)

I will hope for your corrections :)

**Comment by DelirusCrux** [comment]
This propably happens if you have the option for the new skin enabled. those entities and blocks are trying to mimick your skin, but would requierre the default 1.7.10.

I'm not working on Et Futurum tho, so don't know if that's the reason

**Comment by Roadhog360** [comment]
I saw this issue on the SkinPort mod actually and was thinking about integrating the fix I saw there.

**Comment by Khikki** [comment]
Hi, it's me again, I want to ask you what do you think about the 1024x512 and 1024x1024 skins? :)

Actually here is an example of how this is done in SkinPort. 
![2021-02-11_04 20 09](https://user-images.githubusercontent.com/35336209/107596746-4eff3200-6c21-11eb-88cf-da57e80df486.png)
As I recall, Optifine can do that, too. If only there was a custom host server.

And how it looks now in Et Futurum Rq.
![2021-02-11_04 15 35](https://user-images.githubusercontent.com/35336209/107596826-971e5480-6c21-11eb-9ea7-7dd863ce461a.png)

Do you think it is not difficult to add support for hd-skins? :)

**Comment by Roadhog360** [comment]
This would be more fit to ask as its own issue, where I can mark it as a feature request.

**Comment by Khikki** [comment]
Sure, no problem.

**Comment by Roadhog360** [comment]
I fix issues as I see fit. This is not a simple request so please be patient.

**Comment by Roadhog360** [comment]
Ok, so I've started working on a fix for this. 2.1.2 will at least see *some* progress on this. For one, giant miners render normally, but with the default 1.7 model. I'll see if I can get them to use the Et Futurum model. With permission of the mod author of SkinPort, the SkinPort model and renderer is partially applied.

![2021-04-03_12 40 19](https://user-images.githubusercontent.com/11903511/113485094-efcbda00-9479-11eb-86d7-37d22ecfb86a.png)
![2021-04-03_12 40 17](https://user-images.githubusercontent.com/11903511/113485096-f22e3400-9479-11eb-921a-00e992c46b4b.png)

**Comment by Roadhog360** [comment]
How does it look with SkinPort compared to this? I am not sure with the way the giants work that it's possible to use the Alex model, but at least we have this now, which is good!

**Comment by quentin452** [comment]
try confighelper-1.2.4.8 in curseforge to ftry to fix conflicts

**Comment by Roadhog360** [comment]
It is not or this would be closed.

**Comment by OMGICE** [comment]
Is there really no solution?  :0

**Comment by Roadhog360** [comment]
No, as I said multiple times now I don't know how to fix it. Please stop asking.

**Comment by Roadhog360** [comment]
I will consider this the solution for now. Thank you for showing this.

**Comment by Roadhog360** [comment]
I have decided to close this issue as there are more options for skin backporting that is far more stable than my own. I now recommend a different mod for this. Mods like Ears or MorePlayerModels are better options for this.
