### ISSUE TITLE
Et Futurum's Daylight Sensor tweaks breaks Witchery's Solar Collectors

### ISSUE THREAD

**Issue by DrParadox7** [Roadhog360/Et-Futurum-Requiem#80]
As per title.
[Witchery's Solar Collector](https://sites.google.com/site/witcherymod/sunlight-collector) do not function when Et Futurum's Daylight Sensor Tweaks are on.

> Collectors must be placed next to a Daylight Sensor and a quartz sphere placed on each. If a sphere receives all of the sunlight from the break of dawn, though to midday it will be charged:
![image](https://user-images.githubusercontent.com/47131096/137038575-267fd290-d733-4ab4-adcc-cee6fc40ecae.png)

This does not occur with Et Futurum.

Just making you aware.

**Comment by DarianLStephens** [comment]
It could probably also have just checked for an instance of that block.

**Comment by makamys** [comment]
What if we replaced `Blocks.daylight_detector` with Et Futurum's instance? That sounds like it would fix the Witchery issue, but I'm not sure if it would break everything else.

**Comment by Roadhog360** [comment]
This has been fixed in the latest beta. Using the regular daylight sensors instead of a pointless copy is now the default. For compatibility, simply don't invert the sensor.
