### ISSUE TITLE
[Suggestion] Option to increse ladder hitbox

### ISSUE THREAD

**Issue by XXxinsanityxX** [Roadhog360/Et-Futurum-Requiem#81]
This is to match the hitbox of the ladder to the one of the open trapdoor and doors, It would allow for ladders to be climbed past the trapdoors instead of hitting your head on them.

![HitBox](https://user-images.githubusercontent.com/42390377/137427118-b3c037e5-b358-49db-a329-2bea3cb4cd6c.png)

**Comment by XXxinsanityxX** [comment]
Yes this was fixed in newer versions not sure when.

This is 1.16.5 the ladder matches the trapdoor.
![2021-10-14_23 36 55](https://user-images.githubusercontent.com/42390377/137432993-9e0de8d4-4e3e-45ec-9c53-fad7ae2e9339.png)

The increase in the hitbox seems to be from the back since the ladder renders one pixel forward.
![2021-10-14_23 37 38](https://user-images.githubusercontent.com/42390377/137433089-46355cdf-284b-440a-abfd-6f99ceecdc51.png)

**Comment by GregoriusT** [comment]
Should be enough Info for when Roadhog is back. ^^

**Comment by Roadhog360** [comment]
Forgot to remove enhancement label, suggestions now belong in the discussions tab.
