### ISSUE TITLE
Unable to obtain polished deepslate

### ISSUE THREAD

**Issue by sidnoway** [Roadhog360/Et-Futurum-Requiem#85]
[The crafting recipe appears to be missing. ](https://i.imgur.com/fi5TK4h.png)

This could be an incompatibility with one of my many mods, so if anyone else is/isn't having this issue, please reply!

**Comment by Roadhog360** [comment]
![image](https://user-images.githubusercontent.com/11903511/140633074-d96a9d8b-e2b3-4fd7-8712-22d014b88823.png)

**Comment by Roadhog360** [comment]
Are you using the beta, and what mods are installed?

**Comment by sidnoway** [comment]
Yup, it was a mod conflict. My bad. Should've tested on a clean install.

**Comment by Roadhog360** [comment]
Again, I need more info so I can investigate a fix please

**Comment by sidnoway** [comment]
Sorry about the wait. I narrowed it down to [Convenient Recipes](https://www.curseforge.com/minecraft/mc-mods/convenient-recipesl). It's a really niche mod, so if you wouldn't want to fix it, I would not blame you.

**Comment by GregoriusT** [comment]
You meant to link to https://www.curseforge.com/minecraft/mc-mods/convenient-recipes without the lowercase l at the end of the Link. ;)

Also funnily enough, my first thought was "oh shit, GT6 must be breaking something", followed by "Wait, this person has a ton of Iron equipment, nobody in their right mind would do that in GT6!" XD

**Comment by Roadhog360** [comment]
Was able to reproduce, however I cannot fix this because the mod is closed-source so I have no way of knowing what causes the recipe to stop working.

**Comment by DarianLStephens** [comment]
You could also just do the same thing with a Crafttweaker script.
It's an old mod, and is probably not done particularly well.

**Comment by Roadhog360** [comment]
Yeah, that is actually a far better idea. Make the recipes exactly the way you want and only have the ones you want this way.
