### ISSUE TITLE
Disabling replacement system removes et futurum enchanting tables entirely [BETA 3.1]

### ISSUE THREAD

**Issue by tyrael93** [Roadhog360/Et-Futurum-Requiem#88]
Before I updated to the beta release, I could use both regular vanilla minecraft enchanting tables and Et futurum enchanting tables. Now I can only choose between one or the other, because of this line:
> Requires tile entity replacement to be enabled in function.cfg [default: true]
>B:enableNewEnchantingTable=true

If I set     I:tileReplacementMode to -1, disabling the replacement itself, that line
>B:enableNewEnchantingTable

autosets itself to "false". That means I lose the ability to craft the et futurum enchanting table, since is removed from NEI and the game entirely. If I decide to set it to 0 (always replace with new), I can only use the new table and if I set it to 1(always replace with old) I can only use the old tables. There is no way to go back to the previously working version with both tables available.

See, the real problem here is that HEE spawns enchanting tables by default in some dungeon mini-boss towers, and I have tailored my modpack to have those (vanilla enchanting tables) to be an inferior version of the enchanting table, that requires additional endgame thaumcraft components to craft the "advanced" version (the infusion enchantments have also been removed), which is the et futurum table, which is much more flexible. Crafting those tables requires finding (cannot be crafted!) a vanilla enchanting table in the end for that specific reason.

Now I don't have that option anymore. 

Please, add the option to have both vanilla and et futurum enchanting tables back, since as it is I cannot change the HEE structure spawns at all, and thus all newly spawned tables would be either et futurum ones (nullifying the recipe) or "un-upgradeable" vanilla ones (again, nullifying the recipe).

**Comment by Roadhog360** [comment]
I can't add back an option I never removed. I don't know what is setting your config option to false, but nothing in my code does this, and I cannot get this to happen. Please state your mods list and test a client which only has Et Futurum Requiem installed.
![image](https://user-images.githubusercontent.com/11903511/142969473-c3f66ff4-f1fb-47ad-87a6-1562edf33a6d.png)

**Comment by tyrael93** [comment]
:worried: 
Cannot reproduce either, both can be acquired properly
super sorry to bother, I don't know how that happened but I'm entirely sure I doofus'd that one along the way.
![2021-11-23_08 02 55](https://user-images.githubusercontent.com/5557920/142982745-54d511e9-1da4-4bfa-903c-de8b336f7a04.png)
