### ISSUE TITLE
Crashes with Smart Moving again

### ISSUE THREAD

**Issue by ThePwnd** [Roadhog360/Et-Futurum-Requiem#94]
Hi all,

I had encountered this issue with older versions of ETR and the original ET.  Playing with this mod and Smart Moving causes the game to crash with a reference to the player model:

java.lang.ClassCastException: ganymedes01.etfuturum.client.model.ModelPlayer cannot be cast to api.player.model.ModelPlayer

Here's the pastebin with the full text of the error message - https://pastebin.com/wVSjGetR

In past versions of ET and ETR, I had simply set "enablePlayerSkinOverlays"=false, and that fixed the crash.  Now with the introduction of 2.3, and splitting the configs into multiple files, I don't see this option any longer, nor do I see a comparable config option.  As such, I am unable to fix this crash myself.  Is it possible to restore that config option to one of the files?

**Comment by Roadhog360** [comment]
This option is kocated in ConfigFunction.cfg.

**Comment by ThePwnd** [comment]
Evidently I'm blind.  I swear I had gone through the configs doing a find on "skin."  I guess I must have skipped that on the functions config.  Thanks for pointing that out!
