### ISSUE TITLE
Et Futurum crashes with AoA Deeplands Dimension

### ISSUE THREAD

**Issue by Daghara2** [Roadhog360/Et-Futurum-Requiem#96]
I entered the deeplands dimension and I crashed
here's the crash report
https://pastebin.com/Hdz1GMz0

**Comment by Roadhog360** [comment]
Does it work in this build here?
https://github.com/Roadhog360/Et-Futurum-Requiem/actions/runs/1628397517

**Comment by Protogen67** [comment]
> Does it work in this build here? https://github.com/Roadhog360/Et-Futurum-Requiem/actions/runs/1628397517

doesn't work in 2.3.1

**Comment by Roadhog360** [comment]
Okay, the build I sent you is newer than that.

**Comment by Roadhog360** [comment]
> > Does it work in this build here? https://github.com/Roadhog360/Et-Futurum-Requiem/actions/runs/1628397517
> 
> doesn't work in 2.3.1

Okay, the build I sent you is newer than that, that doesn't answer my question.

**Comment by Protogen67** [comment]
how do I download?

**Comment by Roadhog360** [comment]
Click on the "build" button with the green checkmark next to it.

**Comment by makamys** [comment]
> Click on the "build" button with the green checkmark next to it.

That just shows the build log. Instead, click "**Package**" in the "**Artifacts**" section on the bottom of the page to download the build.
Here' a direct link to it: https://github.com/Roadhog360/Et-Futurum-Requiem/suites/4772782874/artifacts/132913514

**Comment by Roadhog360** [comment]
Thank you.

**Comment by Protogen67** [comment]
sorry for being a month late 
it still doesn't work

**Comment by Roadhog360** [comment]
Because the mod hasn't been updated yet. The current version isn't magically going to have the fix.

**Comment by Roadhog360** [comment]
Using the build I sent you or the latest release?

**Comment by Protogen67** [comment]
the build you sent me

**Comment by Roadhog360** [comment]
I'm sorry, I looked into it and can't figure out why this is. Perhaps the modded generation is calling world generators too early? I can't tell.
