### ISSUE TITLE
After the enchanting table is placed in the server, mining reappears in place

### ISSUE THREAD

**Issue by mcmso** [Roadhog360/Et-Futurum-Requiem#97]
mod version:2.3.1r
forge:1614
server core:THERMOS 58

I'm sorry he didn't crash

**Comment by Roadhog360** [comment]
I don't know what this means. Can you please elaborate?

**Comment by mcmso** [comment]
**Describe the bug**
After the enchanting table is placed in the server, mining reappears in place

**To Reproduce**
Steps to reproduce the behavior:
1. Place the enchantment table
2. Break the enchantment table
3. Enchantment Table appears again

**Mod Incompatibilities**
_If this was a mod incompatibility, what are the possible suspects? If you're not 100% sure, you can still list your suspected mods here, just tell me if you're not certain they actually cause it._

**Mod List**
_If you have posted a crash report above or this is not a mod incompatibility, you can skip this. If you're filling this out because of a mod incompatibility that isn't a crash, crash reports generate a mods list you can copy. Please use Pastebin if it is large. If you don't have an up-to-date crash report, you can hold F3 + C for 10 seconds while in a world to crash the game, which will give you a crash report._

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Any other info I may have missed. If you know the code which causes the error please post a link to it.
https://user-images.githubusercontent.com/46519955/147886849-156b323c-2249-4124-87e1-c0c77fbbc0ac.mp4

e

**Comment by Roadhog360** [comment]
You forgot to provide your mods list.

**Comment by mcmso** [comment]
> 

![image](https://user-images.githubusercontent.com/46519955/147887405-04dd9047-58f7-4c72-9374-17700ecbec17.png)
![image](https://user-images.githubusercontent.com/46519955/147887438-9926a15e-40e8-4394-9efb-bb2424d59e6b.png)
![image](https://user-images.githubusercontent.com/46519955/147887443-30fb92c8-9fde-40dc-9e53-e849b4aaa2c4.png)

**Comment by mcmso** [comment]
This is not the case in single-player games

**Comment by Roadhog360** [comment]
Would have been really helpful to know that last bit sooner. Will do some testing. Thanks.

**Comment by mcmso** [comment]
> Would have been really helpful to know that last bit sooner. Will do some testing. Thanks.

The same thing happened with "minecraft::beacon".I suspect they are of the same nature.
ps.This has not happened at Anvil
This only happened on items vanilla took out
This is not the case with item in the diagram
![QQ截图20220103180116](https://user-images.githubusercontent.com/46519955/147918445-d5013b42-9cc1-4f87-a3b2-36dc257a9967.png)
My English is not very good, I hope you can understand what I express

**Comment by Roadhog360** [comment]
I fully understand, I'll need time to test it, but I will get back to you.

**Comment by mcmso** [comment]
This is no longer happening when I update to the Forge server.

**Comment by mcmso** [comment]
" enchanting talbe"   is not supported the Exu's divisionSigil ceremony
