### ISSUE TITLE
Snowman model changed to Ender Dragon, but Ender Dragon is another model that cause the client crash

### ISSUE THREAD

**Issue by FutureSonic-TH** [Roadhog360/Et-Futurum-Requiem#98]
I remember that I got this bug when **old discontinued Et Futurum** updated to **Et Futurum Requiem**. At that time I just suddenly discovered this soon. In past, I didn't know what a mod caused this, because I added not only Et Futurum Requiem. But from now I tested this by deleting all new mods that I added in past. And when I delete Et Futurum Requiem - this bug is gone and all is okay (Fun fact - deleting Et Futurum is breaks the game world). 

**If this will be useful I deleted Et Futurum after this mods:** 

- ASMC-1.7.10-1.0.2

- campfirebackport-1.7.10-1.9

- netherlicious-2.6.0

- NotEnoughPets-1.7.10-2.3.0

- VillageNames-1.7.10-4.3.1

**I recorded a video to demonstrate this bug and here I reproduce this.** Here is the link - https://youtu.be/rmN8Lv6cnYs .
So what you can see in the video, Snowman has his own logic, but the player model changed to Ender Dragon with flying animation and boss bar. This is super laggy when you have 20 Snowmans...

And in this case, I tried to check what a model will be in Ender Dragon and tried to revive the dragon with a crystal. And after that, I got the client crash. In the crash report when I saw what problems it's said that It's can be a Zombie Villager that maybe cannot be rendered (maybe).

Here is the crash report - https://pastebin.com/9E7CrUjG .

**_Tested version of Et Futurum Requiem is 2.0.2_**

**Comment by Roadhog360** [comment]
Bugs on older versions are not supported as they may have already been fixed. Please see if you can get it to happen in the new update.
